### ISSUE TITLE
Using user public in Odoo

### ISSUE THREAD

**Issue by NguyenAnhTuyen** [Odoo-mobile/framework#105]
Hi everyone, I'm newbie android and Odoo mobile, I'm building a mobile application an e-commerce. I have addon using Odoo.I want to use public user to connect applications instead of admin for the first time as login. 

Could you help my with the application? Thank so much for reading.
 
P/s: My english is not good, I hope you understand what I my mean.

**Comment by dpr-odoo** [comment]
Hello @NguyenAnhTuyen 

Currently JSON-RPC does not support to login with public user. For now, just create one user with some of your required rights and use that user for default user in application to get details from server.
