### ISSUE TITLE
How to use OSelection

### ISSUE THREAD

**Issue by sylwek845** [Odoo-mobile/framework#107]
Hi,
I was wondering how to use OSelection in layout, I can't find it in the documentation.

This is what I've tried but it does not show anything 

 <odoo.controls.OSelectionField
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:fieldLabelColor="@color/theme_secondary"
                        app:fieldName="pump_mod_type"
                        app:fieldTextAppearance="?android:textAppearanceMedium"
                        app:iconResource="@drawable/ic_action_notes_content"></odoo.controls.OSelectionField>

and I have problem with OBooleanField because some fields seems to not apper, does it only shows the ones with true value ? 

Thanks

**Comment by dpr-odoo** [comment]
Hello @sylwek845 

Here is blog for understanding and working with OSelection field  https://goo.gl/AMWR2J
