### ISSUE TITLE
Starting with Odoo Mobile

### ISSUE THREAD

**Issue by shynejocef** [Odoo-mobile/framework#109]
Hi,
 I'm newbie in Odoo. I downloaded the framework and installed in device, and successfully logged into database using my self hosted URL(Basically a school management system). But I couldnt get any details in the list.
I tried the following
- created a new addon Student same as the Customer pointing toward the model StudentStudent.java
-in my database there is about 413 tables 
-first of all I just want list of all the students for that I added all the columns in the ResPartner the to StudentStudent.java. Added Student in Addons.java and StudentStudent in BaseModels. Now I'm getting a nullpointerexception at public void onLoadFinished(Loader<Cursor> loader, Cursor data) , the Cursor is null there.
this what my respartner looks like.
<img width="960" alt="2015-12-23" src="https://cloud.githubusercontent.com/assets/8074379/11974113/2ac65254-a987-11e5-983b-63aaba2e39ec.png">

What am I doing wrong??

**Comment by dpr-odoo** [comment]
@shynejocef 

Refer documentation for understanding how to create addon, register model and make service to sync data from server. 

It will show you example for tasks. Just replace model with you model.
