### ISSUE TITLE
Run app on IDE android return java.lang.NullPointerException

### ISSUE THREAD

**Issue by ytgdoc** [Odoo-mobile/framework#111]
Hi , i got error when i login to app Odoo-mobile/framework on virtual device. I really don't know this error , please tell me how i can to fix this error. thanks alot everyone
This is error i got it
 Unexpected response code 404 for https://www.odoo.com/auth_oauth/oea?access_token=ea92592c70bd42e49616db2ebccec83c&scope=userinfo&expires_in=3600.0&response_type=token&client_id=null&db=openerp

**Comment by dpr-odoo** [comment]
@ytgdoc 

Can you please put trace you got from server ?

**Comment by dpr-odoo** [comment]
Hope your problem resolved. Closing issue.

**Comment by ytgdoc** [comment]
yes, i has research a the way to resolve this my issued, thanks for care it. sorry my skill english verry poor.
