### ISSUE TITLE
Your Documentation is not working for mobile framework

### ISSUE THREAD

**Issue by dineshbalu** [Odoo-mobile/framework#112]
Hi,

I'm trying to start with your mobile framework , but there is a crash.

I have mailed your support team , but no reply yet.

Tried your documentation link http://mobile.odoo.co.in/v2/ , Doesn't work

Can you help me?

**Comment by dpr-odoo** [comment]
@dineshbalu 

Currently server is down for sometime. You can refer the latest documentation from http://odoo-mobile-doc-v2.readthedocs.org
