### ISSUE TITLE
How to open the project from Android Studio.

### ISSUE THREAD

**Issue by VicoMaster** [Odoo-mobile/framework#113]
Good day, greeting from Colombia.
I try to open the framework for Android Studio but I get errors like "Application name and Application id must be different than 'com.odoo' and odoo"
I am new development, I appreciate it very much a very detailed description to open the project and to fully manipulate the proyect " also open it in a device".

not know how to thank you for this help, but, going to win the heaven with me.

I'm sorry for me english  :)

http://imgur.com/ZduHOCf
http://imgur.com/KClp5Ww

Version Android Studio  1.5.1

**Comment by dpr-odoo** [comment]
@VicoMaster  

You need to change framework applicationId and applicationName. Gradle compile ignored if it is same as Odoo and com.odoo ..

https://github.com/Odoo-mobile/framework/blob/master/app/build.gradle#L9,L12.
