### ISSUE TITLE
Send email is error about my phone

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#117]
public static void requestMessage(Context context, String email) {
        if (!email.equals("false") && !email.equals("")) {
            Intent intent = new Intent(Intent.ACTION_SENDTO);
            intent.setType("text/plain");
            intent.setData(Uri.parse("mailto:" + email));
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(intent);
        }
    }

when the phone is not email app ,  this code will be error,so i think to it need to add a judge.......for example:

   public static void requestMessage(Context context, String email) {
        if (!email.equals("false") && !email.equals("")) {
            Intent intent = new Intent(Intent.ACTION_SENDTO);
            intent.setType("text/plain");
            intent.setData(Uri.parse("mailto:" + email));
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            if (intent.resolveActivity(context.getPackageManager()) != null) {
                context.startActivity(intent);
            } else {
                OLog.log("mark.ma, no email app !!!!!");
            }
        }
    }

These are my recommendations。Thanks

**Comment by dpr-odoo** [comment]
Can you try with latest update. Thanks.
