### ISSUE TITLE
Sync data by calling method

### ISSUE THREAD

**Issue by AsKaeternam** [Odoo-mobile/framework#118]
Hello everyone, 

Is there a way to sync data based on a call method, 

for example call "fetch_message" to get messages from Odoo ?

Maybe in the getSyncAdapter() method in my OSyncService ?

Best regards

**Comment by dpr-odoo** [comment]
Currently with ``OSyncService`` not possible.

**Comment by adam-nadar** [comment]
@AsKaeternam why don't you just try to read data at once from server by read method and populate the local DB
