### ISSUE TITLE
UI Issue with Different Screensize

### ISSUE THREAD

**Issue by synconics** [Odoo-mobile/framework#119]
Hello,

We are using latest framework and found some UI issue in different screen size,
**Screen Size : 4.5"** [Working fine]
**Screen Size : 5.5"** [Top toolbar in form view is overlapping with notification panel.] 

**Screenshot:**
https://drive.google.com/file/d/0B9e6HdcSFq29T3U1VnlaX2U0SXM/view?usp=sharing

Please provide solution ASAP,

Thanks.

**Comment by dpr-odoo** [comment]
@synconics 

Which android version you are using in device screen 5.5 ??

**Comment by synconics** [comment]
@dpr-odoo 

We are using  Samsung Note 2 (Android 4.4.2 [API 19])

**Comment by dpr-odoo** [comment]
@synconics 

Issue fixed : https://github.com/Odoo-mobile/framework/commit/a7910ff01ce1e07d1408284cadd7c642d78b70f8
