### ISSUE TITLE
Widget : SearchableLive is not working properly on All devices

### ISSUE THREAD

**Issue by synconics** [Odoo-mobile/framework#120]
Hello,

I have used widget : SearchableLive, and tried in few devices,

Issue [Not working] API 19 :  when we select any item from available list, **entire screen is reloaded** and **empty all the fields**.
      i.e : Customers >  Create New > add few text field details then select "Country" from SearchableLive widget > all already filled fields **get reset**.

Moto G : [Working fine] API 21
Samsung Grand 2 : **[Not working] API 19**
Samsung Note2: [Working fine] API 19

Please provide any solution,

Thanks.

**Comment by dpr-odoo** [comment]
@synconics can you try with latest update. Thanks.
