### ISSUE TITLE
O2M Column is not working Properly

### ISSUE THREAD

**Issue by synconics** [Odoo-mobile/framework#121]
Hello,

O2M column is not working with latest framework, whatever Related Column set on O2M column is getting NULL while Dry Run in file : OSyncAdapter.java.

I.e : 
**OrderLine.java**

```
OColumn order_id = new OColumn("Contract", Order.class,
        OColumn.RelationType.ManyToOne);
```

**Order.java**

```
OColumn order_line_ids = new OColumn("Order Lines", OrderLine.class,
        OColumn.RelationType.OneToMany).setRelatedColumn("order_id");
```

Please provide some solution regarding this.

Thanks.

**Comment by dpr-odoo** [comment]
@synconics can you check with latest update. Thanks.
