### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by midhunmadhuk** [Odoo-mobile/framework#124]
Hello friends,
From app to odoo syncing is doing perfect intervals, but from odoo to app syncing while be happening only after relogin.What will be the issue??

**Comment by kasim1011** [comment]
Hey, Does your emulator or phone running lower version than **Kitkat** than you should see [this](https://github.com/Odoo-mobile/framework/issues/165#issuecomment-219676006).

**Comment by dpr-odoo** [comment]
Similar issue will be fixed in #165
