### ISSUE TITLE
Odoo mobile framework import issue

### ISSUE THREAD

**Issue by elprincipe** [Odoo-mobile/framework#126]
I to every one
I'am nex to oddo mobile framework and I have trouble when importing odoo mobile frawork (v2.1.0alpha) as new project. I'am using androidstudio 1.3.  In manifest.xml file there are reference error to xml ressource. I also have here problem referencing activity class. Eg: 
        <activity
            android:name="com.odoo.addons.customers.CustomerDetails"
            android:windowSoftInputMode="adjustPan" />
Here "com.odoo.addons.customers.CustomerDetails" will be marked as red with the message 'cannot resolve symbol ...'.

Also when i'm editing code it is impossible don't see various class create in the project so it is unable to do completion, Type checking ...

I should mention that i don't have all these issue for other project i'm working on without odoo mobile framework.

Hope to have an answer.
Best regards

**Comment by dpr-odoo** [comment]
Can you try with latest update.
