### ISSUE TITLE
Connecting to odoo 9

### ISSUE THREAD

**Issue by lakshman12345** [Odoo-mobile/framework#127]
Hi we had upgraded to odoo9 but we cant able to access odoo9 from android app it is not at all showing database choosing option please help me with that.

**Comment by Abderrahmen** [comment]
Hello, i wonder if you did succeeded  to use the framework with Odoo9? Thank you in advance

**Comment by jzahid** [comment]
i ve been using last version of framweork for a month now. and it's working
perfectly with v9.




*Odoo Integrator, Data integration *
*BI and IT consulting.*

j.zahid@auriumtechnologies.com
tél  0661360233 - 0636898882
fax 0528215738
