### ISSUE TITLE
Directories errors

### ISSUE THREAD

**Issue by meryaam** [Odoo-mobile/framework#133]
Plz heeelp me i import the framework to my eclipse ADT ,two diectories drawable-xxxhdpi & mipmap-xxxhpdi contains a cross ,prevent my project to run

**Comment by jzahid** [comment]
Eclipse ADT is no more supported by android. You better switch to android
studio.




*Odoo Integrator, Data integration *
*BI and IT consulting.*

j.zahid@auriumtechnologies.com
tél  0661360233 - 0636898882
fax 0528215738

**Comment by meryaam** [comment]
Done thnx jzahid :)

**Comment by dpr-odoo** [comment]
@jzahid :+1:
