### ISSUE TITLE
Require custom table name as additional parameter in OColumn constructor for ManyToMany relationship.

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#136]
In my case I've one `Model` which has 2 fields relates to same (another) Model in `ManyToMany` relationship.

    public class AttReport extends OModel {

        OColumn lat = new OColumn("Latitude", OFloat.class);
        OColumn lng = new OColumn("Longitude", OFloat.class);
        OColumn employee_id = new OColumn("Name", HrEmployee.class,
                OColumn.RelationType.ManyToOne);

        // this one
        OColumn employee_absent_ids = new OColumn("Employees Absent", HrEmployee.class,
                OColumn.RelationType.ManyToMany);
        // and, this one
        OColumn employee_present_ids = new OColumn("Employees Present", HrEmployee.class,
                OColumn.RelationType.ManyToMany);

        public AttReport(Context context, OUser user) {
            super(context, "attendance.report", user);
        }

    }

so, when I run the app. my relational table gets override.

    I/OSQLite: creating database.
    V/OSQLHelper: Table Created : mail_message_ir_attachment_rel
    V/OSQLHelper: Table Created : attendance_report_hr_employee_rel // this one
    I/OSQLite: Table Created : attendance_report
    I/OSQLite: Table Created : school_school
    I/OSQLite: Table Created : attendance_report_hr_employee_rel // and, this one
    I/OSQLite: Table Created : odoo_news
    I/OSQLite: Table Created : res_partner
    I/OSQLite: Table Created : mail_message
    I/OSQLite: Table Created : res_country
    I/OSQLite: Table Created : mail_message_ir_attachment_rel
    I/OSQLite: Table Created : ir_model
    I/OSQLite: Table Created : ir_attachment
    I/OSQLite: Table Created : res_users
    I/OSQLite: Table Created : res_company
    I/OSQLite: Table Created : hr_employee
    I/OSQLite: Table Created : mail_message_subtype
    I/OSQLite: Table Created : res_currency
    I/OSQLite: 15 Models registered.

This happens just because of `odoo-mobile` framework's default naming functionality. Now, I can solve this problem only by giving custom name to `relational table`. or please, tell me if there is another approach.

Thanks.

**Comment by dpr-odoo** [comment]
@kasim1011 issue fixed: https://github.com/Odoo-mobile/framework/commit/654554aaf48969f2e7757cabeb197973776e97fb

```java
OColumn test_ids= new OColumn("Partners", ResPartner.class, OColumn.RelationType.ManyToMany)
            .setRelBaseColumn("partner_id")
            .setRelRelationColumn("ref_partner_id")
            .setRelTableName("m2m_rel_table_1");

OColumn test_2_ids= new OColumn("Partners2", ResPartner.class, OColumn.RelationType.ManyToMany)
            .setRelBaseColumn("partner_id")
            .setRelRelationColumn("ref_partner_id")
            .setRelTableName("m2m_rel_table_2");
```

**Comment by kasim1011** [comment]
@dpr-odoo Thank you.
