### ISSUE TITLE
Enhancement Request for OModel::onSyncFinished with onSyncFinishedListener

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#141]
I've two Models named `A` and `ResPartner`. I've one `R.layout.common_listview` uses Model `A` as database. Now, in that screen I'm syncing `ResPartner` using `parent().sync().requestSync(ResPartner.AUTHORITY)`. Now, I want to call `restartLoader()` for Model `A` on very next moment when syncing get finished. so, I require **onSyncFinishedListener**. here's example code snippet.

	parent().sync().requestSync(ResPartner.AUTHORITY)
	                .setOnSyncFinishedListener(new OnSyncFinishedListener() {
	                    @Override
	                    public void onSyncFinished() {
	                        // Here's your code
	                        // getLoaderManager().restartLoader(0, null, A.this);
	                    }
	                });

**Comment by dpr-odoo** [comment]
Hello,

If you are using Loader, there is sync observer that you can implement, It will give you state for syncing state (refreshing) so you can handle your event based on sync state.

Just add observer listener in **onViewCreated** of fragment with your `db()` object : https://goo.gl/LzPs9j

It will implement **onStateChange** method where you can reload your data with restarting loader by checking **refreshing** boolean flag. When sync in progress refreshing will be `true` and when done it will become `false` https://goo.gl/WxcDm4

**Comment by kasim1011** [comment]
@dpr-odoo  Thanks
