### ISSUE TITLE
Customers, suppliers and companies

### ISSUE THREAD

**Issue by YPerezM** [Odoo-mobile/framework#143]
I was testing the app and when I add a customer, it is shown on the right site(customers page). The problem is that when I add a company, it is shown in the companies page and in the customers page too. They appear mixed.

Other problem that I found is that when I try to insert a new supplier, the button save at the top(to finish and add the new supplier) doesn't work.
EDIT: the button works,but add the supplier to the customers list. So in the customers list are all the customers,suppliers and companies mixed. The suppliers pages is empty, and in the companies list appear only the companies(it works perfectly).

If anyone knows how to fix this problems i will be very pleased. Thank you

**Comment by dpr-odoo** [comment]
Hello @YPerezM 

In odoo when you create any company It refer as company as well as customer. (try creating company on odoo it will appear in both customers and company) 

And for suppliers, There is a bug for setting supplier flag and its fixed.

**Comment by YPerezM** [comment]
Thank you very much, now it works better. Instead of open a new thread I’m  going to ask you for one last thing. If I want to delete a item(customer,supplier or company) how can I do? I tried to make a button in the menu_customer_detail.xml that could delete the item selected but the coding its too difficult for me. Don’t know how to delete the item.

**Comment by dpr-odoo** [comment]
@YPerezM 

You can find commit where "Delete" menu added in partner detail form. https://github.com/Odoo-mobile/framework/commit/66b1161599e217f5206571854ae8b30a39b42f78
