### ISSUE TITLE
why i can't see any customer .. ?

### ISSUE THREAD

**Issue by ilyasbahridudak** [Odoo-mobile/framework#148]
![fadsiz](https://cloud.githubusercontent.com/assets/13995486/14890184/4a710576-0d6a-11e6-8621-d933b3724d37.jpg)

is this issues ?

**Comment by kasim1011** [comment]
Try adding your custom `authorities URI` at following two places.

1. inside `AndroidManifest` at sync `<provider>` for `CustomersSyncProvider`.<br/>
Replace<br />
`<provider`<br />
`    android:name="com.odoo.addons.customers.providers.CustomersSyncProvider"`<br />
`    android:authorities="${applicationId}.core.provider.content.sync.res_partner"`<br />
`    android:label="@string/sync_label_customers"`<br />
`    android:multiprocess="true" />`<br />
with <br />
`<provider`<br />
`    android:name="com.odoo.addons.customers.providers.CustomersSyncProvider"`<br />
`    android:authorities="com.odoo.core.provider.res_partner"`<br />
`    android:label="@string/sync_label_customers"`<br />
`    android:multiprocess="true" />`<br /><br />
2. inside `ResPartner` at package `com.odoo.base.addons.res` change `AUTHORITY` to `com.odoo.core.provider.res_partner`

**Comment by kalvian1060** [comment]
Thanks now my project is work...

**Comment by kalvian1060** [comment]
3. Remove Application Id on ResPartner AUTHORITY
4.dont forget change on xml customer_sync_adapter.xml
change to com.odoo.core.provider.res_partner

**Comment by kalvian1060** [comment]
Successfully

**Comment by ghozimahdi** [comment]
statement no 2 ,, meaning replace code  
public static final String AUTHORITY = BuildConfig.APPLICATION_ID +"com.odoo.core.provider.res_partner"; 
to public static final String AUTHORITY = "com.odoo.core.provider.res_partner"; ,, thanks tutorial guys ..
