### ISSUE TITLE
Records of different models

### ISSUE THREAD

**Issue by sylwek845** [Odoo-mobile/framework#150]
Hi,

I want to review other models details, for example I have equipment model and trip model and in trip class I want to check all records from equipment to find some details (not related) . How do I do that ? In my trip class I extended AppCompatActivity because I want to display the info.

**Comment by 74n3r** [comment]
i have some problems .. i cant solve any yet..

**Comment by sylwek845** [comment]
that's fine, I managed to do it myself. thx
