### ISSUE TITLE
sync disabled issue

### ISSUE THREAD

**Issue by merajuddin1** [Odoo-mobile/framework#154]
Database synchronization issue using odoo mobile v3 framework, showing sync is disabled like in screenshot and crashes when clicked after some seconds!!!

![screenshot_2016-05-06-10-19-11](https://cloud.githubusercontent.com/assets/19218496/15064654/566e74f2-1374-11e6-8300-3998f09706a6.png)

**Comment by 74n3r** [comment]
this prolem was solved..  https://github.com/Odoo-mobile/framework/issues/142

**Comment by kasim1011** [comment]
Hey, does your emulator or phone running lower version than **Kitkat** than you should see [here](https://github.com/Odoo-mobile/framework/issues/165).

**Comment by dpr-odoo** [comment]
Similar issue will be fixed in #165
