### ISSUE TITLE
java.lang.NullPointerException - bug

### ISSUE THREAD

**Issue by 74n3r** [Odoo-mobile/framework#155]
how can i solve this problem ?

![2016-05-06_16-47-45](https://cloud.githubusercontent.com/assets/3882613/15075346/8e11e4ce-13ac-11e6-8033-ac720f4ea14b.png)

**Comment by kasim1011** [comment]
give me Model, provide & service class for that riskassessment table.

I guess you've created xml for that give me that too.

& see me how put entry of <provider> & <service> of RiskAsesment in androidManifest xml.

and i hope you've make one entry in config/Addons.java

also i want to see that.


if all above thing is right then this should work.



Thanks & Regards

Kasim Rangwala
Mo: +91 9033780529
________________________________

**Comment by 74n3r** [comment]
thanx bro i was send mail ..
