### ISSUE TITLE
Add product menu 

### ISSUE THREAD

**Issue by YPerezM** [Odoo-mobile/framework#157]
Hello, I am trying to add a new menu with the name "products"(to manage the products in the same way as in the server). 

I have already added into the slider menu a new option called "products". The problem is that I do not know how to uses a different xml in the case of the products, and how to relate the parameters that it needs.

Thank you for the help

EDIT: That is a screenshot from the server with the parameters that I need to create:
![captura de pantalla de 2016-05-09 13 53 36](https://cloud.githubusercontent.com/assets/8902208/15138842/cc378004-1692-11e6-8ac1-c11c6391182f.png)

And that is the slider menu that I have right now, with the option products added:
![screenshot_2016-05-09-13-47-12](https://cloud.githubusercontent.com/assets/8902208/15138873/fd674506-1692-11e6-9e07-6f3a8db2b3da.png)

What I want to do is when you add a new product, it appears the parameters (sale price,can be sold,can be purchased ...)

PD: The screenshots are in Spanish, if you want I can change them to English

**Comment by 74n3r** [comment]
can you sent any screenshoot .

**Comment by 74n3r** [comment]
doesnt matter its understable .. 
did u read this doc maybe its can be help to you.. 
http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/drawer-menu.html
