### ISSUE TITLE
why not update OdooCompatActivity like BaseFragment? 

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#159]
Why not update OdooCompatActivity like BaseFragment? 
For example:
I can  do "parent().sync().requestSync()"  in fragment, but i cannot do it in activity

**Comment by dpr-odoo** [comment]
@mikedream89 

You can do it with below code

```java
SyncUtils.get(context).requestSync(authority);

**Comment by mikedream89** [comment]
@dpr-odoo  
OK , thanks

**Comment by mikedream89** [comment]
@dpr-odoo 
If I requestSync more than one authority，it will part of loss of data.
How can i sync more than one table's datas?
 thanks.

My part of code:
SyncUtils.get(context).requestSync(A);
SyncUtils.get(context).requestSync(B);
SyncUtils.get(context).requestSync(C);
SyncUtils.get(context).requestSync(D);

maybe table C or table D data loss, for example  table C data on phone:

number 40~45 is successful
number 30~39 is failure，data loss

30|true|false|2016-05-12 09:16:14|104|||
31|true|false|2016-05-12 09:16:14|103|||
32|true|false|2016-05-12 09:16:14|102|||
33|true|false|2016-05-12 09:16:15|101|||
34|true|false|2016-05-12 09:16:15|100|||
35|true|false|2016-05-12 09:16:15|99|||
36|true|false|2016-05-12 09:16:15|98|||
37|true|false|2016-05-12 09:16:15|97|||
38|true|false|2016-05-12 09:16:15|96|||
39|true|false|2016-05-12 09:16:15|95|||
40|true|false|2016-05-12 09:16:48|94|21|[910.0]|Pending
41|true|false|2016-05-12 09:16:48|93|23|[906.0]|Pending
42|true|false|2016-05-12 09:16:48|92|24|[905.0]|Pending
43|true|false|2016-05-12 09:16:48|91|25|[875.0]|Pending
44|true|false|2016-05-12 09:16:48|90|26|[874.0]|Pending
45|true|false|2016-05-12 09:16:48|89|27|[872.0]|Pending
