### ISSUE TITLE
How to use @Odoo.onChange()?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#162]
Hi,  partner_name_en can not get value from  partnerIdOnChange
who can tell me my code right or not ? Very Thanks!!

This is my code ：
@Odoo.onChange(method = "partnerIdOnChange", bg_process = true)
 OColumn partner_id = new OColumn("Customer Name English", ResPartner.class,  OColumn.RelationType.ManyToOne).setRequired();
 OColumn partner_name_en = new OColumn("partner_name_en", OVarchar.class).setLocalColumn();
  public ODataRow partnerIdOnChange(ODataRow row) {
        ODataRow data = new ODataRow();
        try {
            ResPartner partner = new ResPartner(mContext, getUser());
            ODataRow customer = partner.browse(row.getInt(OColumn.ROW_ID));
            App app = (App) mContext.getApplicationContext();
            if (app.inNetwork()) {
                ServerDataHelper helper = getServerDataHelper();
                OArguments args = new OArguments();
                args.add(new JSONArray());
                args.add(customer.getInt("id"));
                JSONObject res = ((JSONObject) helper.callMethod("onchange_partner_id", args, new JSONObject()))
                        .getJSONObject("value");
                if (res.has("name")) {
                    data.put("partner_name_en", res.getString("name"));
                } else {
                    data.put("partner_name_en",customer.getString("name"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return data;
    }

**Comment by 74n3r** [comment]
@mikedream89 did u solve ?

**Comment by mikedream89** [comment]
yes

**Comment by 74n3r** [comment]
@mikedream89 congratulations

**Comment by mikedream89** [comment]
By the way,odoo framework support offline operations?

**Comment by 74n3r** [comment]
@mikedream89 
i dont test it  but in my opinion it not will be ..

**Comment by mikedream89** [comment]
ok, @74n3r thanks
