### ISSUE TITLE
In BaseFragment is setHasSyncStatusObserver ,then what is in Activity ?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#163]
In BaseFragment is setHasSyncStatusObserver ,then what is in Activity ?

Who can tell me?thanks!

**Comment by dpr-odoo** [comment]
You can implement for activity as:

https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/support/addons/fragment/BaseFragment.java#L102-L127

https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/support/addons/fragment/BaseFragment.java#L194-L202

https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/support/addons/fragment/BaseFragment.java#L267-L274
