### ISSUE TITLE
I can sync data from web site to my phone ,but i cannot sync data to web site from my phone?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#164]
I can sync data from web site to my phone ,but i cannot sync data to web site from my phone?
this is why? 
@dpr-odoo

**Comment by kasim1011** [comment]
does your phone running lower version than **Kitkat**? have a look at [this](https://github.com/Odoo-mobile/framework/issues/165).

**Comment by dpr-odoo** [comment]
Similar issue will be fixed in #165
