### ISSUE TITLE
Sync not working on Android API level 15 (4.0.3)

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#165]
I've prepare demo for performing `sync` operation [here.](https://github.com/kasim1011/Odoo-mobile-quick-start) which works perfectly on **Android Emulator (Android 6.0)** as well as my device **Moto E XT1022 (Android 5.0.2)** but, it doesn't work on **Sony Tablet S (Android 4.0.3)**. It gets force stop with following `errors`. Any kind of help or suggestions will be appreciated. Thanks in advanced.

```
E/dalvikvm: Could not find class 'android.os.UserHandle', referenced from method com.odoo.App.access$super
E/dalvikvm: Could not find class 'android.app.Application$OnProvideAssistDataListener', referenced from method com.odoo.App.access$super
E/dalvikvm: Could not find class 'android.app.Application$OnProvideAssistDataListener', referenced from method com.odoo.App.access$super
E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.android.tools.fd.runtime.MonkeyPatcher.monkeyPatchExistingResources
E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.android.tools.fd.runtime.MonkeyPatcher.pruneResourceCache
E/dalvikvm: Could not find class 'android.os.UserHandle', referenced from method com.odoo.addons.partners.services.PartnersSyncService.access$super
E/dalvikvm: Could not find class 'android.os.UserHandle', referenced from method com.odoo.core.service.OSyncService.access$super
E/dalvikvm: Could not find class 'android.os.CancellationSignal', referenced from method com.odoo.addons.partners.providers.PartnersSyncProvider.access$super
E/dalvikvm: Could not find class 'android.os.CancellationSignal', referenced from method com.odoo.core.orm.provider.BaseModelProvider.access$super


E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
                  java.lang.ExceptionInInitializerError
                      at android.content.ContentProvider.attachInfo(ContentProvider.java:929)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:4260)
                      at android.app.ActivityThread.acquireProvider(ActivityThread.java:4058)
                      at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:1618)
                      at android.content.ContentResolver.acquireProvider(ContentResolver.java:949)
                      at android.content.ContentResolver.acquireContentProviderClient(ContentResolver.java:984)
                      at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:245)
                   Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                      at android.os.Handler.<init>(Handler.java:121)
                      at android.os.AsyncTask$InternalHandler.<init>(AsyncTask.java:607)
                      at android.os.AsyncTask$InternalHandler.<init>(AsyncTask.java:607)
                      at android.os.AsyncTask.<clinit>(AsyncTask.java:190)
                      at android.content.ContentProvider.attachInfo(ContentProvider.java:929) 
                      at android.app.ActivityThread.installProvider(ActivityThread.java:4260) 
                      at android.app.ActivityThread.acquireProvider(ActivityThread.java:4058) 
                      at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:1618) 
                      at android.content.ContentResolver.acquireProvider(ContentResolver.java:949) 
                      at android.content.ContentResolver.acquireContentProviderClient(ContentResolver.java:984) 
                      at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:245)
```

**Comment by kasim1011** [comment]
I had some research regarding above `errors` on Internet and I've got following.

- [UserHandle](https://developer.android.com/reference/android/os/UserHandle.html) Added in API level 17.
- [Application.OnProvideAssistDataListener](https://developer.android.com/reference/android/app/Application.OnProvideAssistDataListener.html) Added in API level 18
- [ArrayMap](https://developer.android.com/reference/android/util/ArrayMap.html) Added in API level 19
- [CancellationSignal](https://developer.android.com/reference/android/os/CancellationSignal.html) Added in API level 16

Above all comes together in one `framework` which has **minSdkVersion 14**. how this thing is possible.

**Comment by kasim1011** [comment]
I've tried [android-odoo-contacts-2016](https://github.com/odoo-mobile-intern/android-odoo-contacts-2016) to find out whether **sync** is working or not. but, it's working fine on **Android 4.0.3** than why `framework` gives error on sync.

@dpr-odoo Please, fix this bug ASAP.
@74n3r
@merajuddin1
@warp10
@YPerezM

**Comment by YPerezM** [comment]
I am learning by myself so do not know if it is irrelevant, but in my app I could not sync from device to server (sync only worked from server to device). It is rare because it was working fine the sync all the time for me, but I found that the problem is that I add some new OColumns that does not let me sync correctly.

So, in my case, the sync does not work because of a few new columns in the database.

**Comment by kasim1011** [comment]
@YPerezM Thanks for the update.

**Comment by 74n3r** [comment]
@YPerezM @kasim1011 auto sync still doesn't work :/

**Comment by jthanyu** [comment]
I have the same problem.
Have you solved it?
@kasim1011

**Comment by dpr-odoo** [comment]
@kasim1011 can you check it with latest update?

**Comment by kasim1011** [comment]
@dpr-odoo 
@r-mckay 
@mikedream89

Let's take on model **`standard.standard`**. 
At the time of opening the issue. The code was like

	package com.abc.xyz.addons.employees.models;

	public class StandardStandard extends OModel {

		public static final String TAG = StandardStandard.class.getSimpleName();
		public static final String AUTHORITY = "com.abc.xyz.addons.employees.standard_standard";

		OColumn sequence = new OColumn("Sequence", OInteger.class);
		OColumn name = new OColumn("Name", OVarchar.class);
		OColumn code = new OColumn("Code", OVarchar.class);

		public StandardStandard(Context context, OUser user) {
			super(context, "standard.standard", user);
		}

		@Override
		public Uri uri() {
			return buildURI(AUTHORITY);
		}
	}

After solving the Issue the code was look like.

	package com.abc.xyz.addons.employees.models;

	public class StandardStandard extends OModel {

		public static final String TAG = StandardStandard.class.getSimpleName();
		public static final String AUTHORITY = "com.abc.xyz.addons.employees.models.standard_standard";

		OColumn sequence = new OColumn("Sequence", OInteger.class);
		OColumn name = new OColumn("Name", OVarchar.class);
		OColumn code = new OColumn("Code", OVarchar.class);

		public StandardStandard(Context context, OUser user) {
			super(context, "standard.standard", user);
		}

		@Override
		public Uri uri() {
			return buildURI(AUTHORITY);
		}
	}

Now, in 2nd code snippet the `AUTHORITY` is exactly same as package name. This prevents force stops in various devices. I want to add another working snippet 

	public class ResPartner extends OModel {
		public static final String AUTHORITY = BuildConfig.APPLICATION_ID +
				".core.provider.content.sync.res_partner";
	}

So, Both 2nd & 3rd is working. This thing makes me confuse which snippet to use for better practice. We want some words from @dpr-odoo on this?

**Comment by dpr-odoo** [comment]
When dealing with Sync Service you need to take care of following things:

For sync service with sync adapter you need four components:

1. Service https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/addons/customers/services/CustomerSyncService.java 
2. Content Provider https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/addons/customers/providers/CustomersSyncProvider.java 
3. XML file (sync-adapter) https://github.com/Odoo-mobile/framework/blob/master/app/src/main/res/xml/customer_sync_adapter.xml
4. Entry of service and provider in Manifest file https://github.com/Odoo-mobile/framework/blob/master/app/src/main/AndroidManifest.xml#L87-L104

In all these component ``AUTHORITY`` is commonly shared with each other that links each of the component together. 

Also when user start sync from settings->account android will trigger ``sync-adapter`` that we have created in xml and linked with sync service which has ``AUTHORITY``. 

``authority`` can by any valid string but for better practice, we create it starts with ``applicationId`` so we get unique authority. 

If you are using custom authority, you have to pass it to ``sync_adapter.xml``, ``ModelDataProvider`` and ``authority`` string to Manifest with ``Provider`` 

Hope this will help to understand the working of sync service with sync-adapter and authority.
