### ISSUE TITLE
[Question]  Is Odoo framework has this function like Odoo function (next_by_code)?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#167]
This is odoo's function: 
vals['name'] = self.pool.get('ir.sequence').next_by_code(cr, uid, 'quality_control') or '/'

If i want to do it on my phone ,i will use which framework's function?

Thanks!

**Comment by kasim1011** [comment]
Please, Don't compare it with Python base framework. this is complete different thing

**Comment by dpr-odoo** [comment]
No any method available but, you can do it by calling ``callMethod``

Get ``getServerDataHelper()`` from model object and call method with your required parameters

```java
ResPartner partner = new ResPartner(context ,null);

String model = "ir.sequence";
String method = "next_by_code";

OArguments args = new OArguements();
args.add("quality_control")

partner.getServerDataHelper().callMethod(model, method, args, new HashMap(), new HashMap());
```

Note that you need to check for method arguments before passing it.
