### ISSUE TITLE
Can i sync one row from server ?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#168]
I want to search on server,if i get one data, can i sync this one to my phone database?

This framework can be implemented?

Ｔｈａｎｋｓ!

**Comment by sylwek845** [comment]
can you give us some more details, what do you mean by "get one data" ?

**Comment by mikedream89** [comment]
sorry ,a data

**Comment by kasim1011** [comment]
@mikedream89 Please, explain your issue in more detail

**Comment by mikedream89** [comment]
@kasim1011 
I want to sync to specify a data from the server side, when I know the id of the data.

**Comment by mikedream89** [comment]
i mean:
If network available i will search on live server  , when i found out that record exist , how to let that record available locally?   
thanks

**Comment by dpr-odoo** [comment]
@mikedream89 

Just get id of that record, and call ``quickSyncRecords()`` will sync that record to local database. https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/orm/OModel.java#L1109-L1114

Pass domain with record id and call method from model object.
```Java
ODomain domain = new ODomain();
domain.add("id", "=", 12);

ResPartner partner = new ResPartner(context,null);
partner.quickSyncRecords(domain);

```
**Note:** You need to call it in background thread such AsyncTask
