### ISSUE TITLE
Odoo Database not updated.

### ISSUE THREAD

**Issue by sylwek845** [Odoo-mobile/framework#170]
Hi, I'm trying to update the db from my listview(by clicking on image), the local db seems to be updated but not the one in odoo server, any ideas ? 

I use the following code 

this is inside my listview adapter

@Override
                    public void onClick(View v)
                    {
                        Log.i("State img", "State onclick");
                        CmmsTripDestination cmmsTripDestination = new CmmsTripDestination(getContext(), null);
                        ODataRow oDataRow = cmmsTripDestination.browse(row.getInt(OColumn.ROW_ID));

```
                    if(!oDataRow.getString("state").equals("5")) {                     
                    OValues oValues = oDataRow.toValues();
                    String updatedState = changeState(oDataRow.getString("state"));
                         oValues.put("state", updatedState);
                         oValues.put("description","Test");


                       boolean t = cmmsTripDestination.update(oDataRow.getInt(OColumn.ROW_ID),oValues);
                       Toast.makeText(getContext(),String.valueOf(t),Toast.LENGTH_SHORT).show();
```

Ps. I can update the data through the form.

**Comment by sylwek845** [comment]
I solved the issue although I'm not sure if that's bug or there is other way of doing it so I will leave the case still Open for now.

So the issue was when I was calling ODataRow.toValues(), I was getting all the data including _writing_date etc. and then the app was not updating the server data. To fix this I created new method in ODataRow class just to get the data without _writing_date, _is_active etc and it worked. Here's the code if anyone needs it but it's just hack and it's not proper code.

`public OValues toModelValues(Class c) {
        Field[] fields = c.getFields();
        OValues values = new OValues();
        HashMap<String, Object> data = getAll();
        for(int i = 0; i < fields.length;i++) {
            if (fields[i].getType() == OColumn.class) {
                if (fields[i].getName().charAt(0) != '_')
                    values.put(fields[i].getName(), data.get(fields[i].getName()));
                else if (fields[i].getName().equals("_id"))
                    values.put(fields[i].getName(), data.get(fields[i].getName()));
            }
        }
        return values;
    }`

To use it you need OModel class parameter, ie oDataRow.ToModelValues(ResUser.class)

**Comment by kasim1011** [comment]
@sylwek845 useful answer.
