### ISSUE TITLE
android.database.StaleDataException: Attempting to access a closed CursorWindow.Most probable cause: cursor is deactivated prior to calling this method.

### ISSUE THREAD

**Issue by tonysumi** [Odoo-mobile/framework#177]
The app keep on crushing when I try to edit the customer for more than one times.
1) select customer
2) In bottom-sheet, select the edit.
3) Go back and then select the edit.
4) Above said error appears 

It's says "Attempting to access a closed CursorWindow.Most probable cause: cursor is deactivated prior to calling this method."
How do I fix this error? Please help.
@dpr-odoo
@asa-odoo 
@sla-odoo

**Comment by dpr-odoo** [comment]
Related to ``BaseModelProvider`` fix will done in #243
