### ISSUE TITLE
help !!!!

### ISSUE THREAD

**Issue by ibrahim-lahribli** [Odoo-mobile/framework#178]
hi there im devloping an apps using odoo mobile framework but im not good on JAVA so do you have any tutorial that can help me and thanks for you attention

**Comment by YPerezM** [comment]
@kasim1011 created a quick start project that maybe help you to learn something about the Odoo mobile development

**Comment by ibrahim-lahribli** [comment]
@YPerezM thanks man thanks I appreciated your help but i looking for tutorials

**Comment by ibrahim-lahribli** [comment]
@YPerezM <https://github.com/YPerezM> thanks man thanks I appreciated your
help but i looking for tutorials

2016-06-02 9:31 GMT+02:00 YPerezM <notifications@github.com>:

**Comment by asa-odoo** [comment]
@ibrahim-lahribli 

here is developer documentation - http://mobile.odoo.co.in/v2/

**Comment by ibrahim-lahribli** [comment]
@asa-odoo thanks man for replying me but this is my first time working with java so i didnt inderstand that documentation

**Comment by asa-odoo** [comment]
@ibrahim-lahribli 
This is the way you can learn development with Odoo Mobile framework with the help of documentation; but before you start to learn odoo mobile framework you need to learn first Java and Android Development. (https://developer.android.com/training/index.html)

**Comment by ibrahim-lahribli** [comment]
@asa-odoo thanks man that may help me

**Comment by 74n3r** [comment]
@kasim1011 .. Already wrote odoo mobile quick starter for new users..

**Comment by ibrahim-lahribli** [comment]
@74n3r yep man but the the problem i dont have java basics so im turning now to java before starting with this framework

**Comment by 74n3r** [comment]
@ibrahim-lahribli good selection
