### ISSUE TITLE
how can i declare  BaseFragmentin's class in Android manifest 

### ISSUE THREAD

**Issue by 74n3r** [Odoo-mobile/framework#179]
![tt](https://cloud.githubusercontent.com/assets/3882613/15819647/311c6286-2bed-11e6-8219-94dafdd29f34.png)

hi guys have ur .. any idea ?

**Comment by asa-odoo** [comment]
@74n3r  
please refer this documentation for fragment : https://developer.android.com/training/basics/fragments/index.html
Fragment is a part of an activity, you can not declare it in manifest
