### ISSUE TITLE
SqLite "No such column" error issued on a (supposedly) properly declared OColumn on Android 6

### ISSUE THREAD

**Issue by warp10** [Odoo-mobile/framework#180]
I'm having a very weird error with an OModel I configured as follows:

```
public class ProjectFeedTask extends OModel{
    public static final String TAG = ProjectFeedTask.class.getSimpleName();
    public static final String AUTHORITY = "com.odoo.addons.projects.project_feed_tasks";


    OColumn feed_id = new OColumn("Feed", ProjectFeed.class, OColumn.RelationType.ManyToOne);
    OColumn name = new OColumn("Name", OVarchar.class);
    OColumn user_id = new OColumn("Assigned to", ResUsers.class, OColumn.RelationType.ManyToOne);
    OColumn deadline = new OColumn("Deadline", ODateTime.class);
    OColumn description = new OColumn("Description", OText.class);
    OColumn task_id = new OColumn("Task", ProjectTask.class, OColumn.RelationType.ManyToOne);

    public ProjectFeedTask(Context context, OUser user) {
        super(context, "project.feed.task", user);
    }

    @Override
    public Uri uri() {
        return buildURI(AUTHORITY);
    }
}
```

The app builds fine, the database is properly created, nevertheless the column task_id is not created at all, as I checked via adb shell and sqlite3. In fact, when I try to sync the model, I get the error:
`E/SQLiteLog: (1) no such column: task_id`
As far as I can see, the model should be properly declared, and that particular M2O relationship too. feed_id, another M2O field, is properly created on the db as well. If you are wondering about ProjectTask.class, its model is correctly instantiated and created on Android, and syncs perfectly.

Curiously enough, I'm getting this error only on a Nexus 5X running Android 6. Even more curiously, an emulated Nexus 5X running Marshmellow works great, and any other device I have with Android 5 works great. So, I'm wondering if I did something wrong, or if there is some kind of bug with OMF on Android 6. Any idea?

**Comment by kasim1011** [comment]
@warp10 Did you try uninstalling than reinstalling app on that device Nexus 5X running Android 6. because on other devices you perform fresh install & may be it's the reason behind it works perfectly.

**Comment by warp10** [comment]
Hence I don't get any similar issue anymore after changes I did to my project so far, I guess It was my own fault (well, small doubts on that) and got it fixed, some way. Closing this issue right now.
