### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by jthanyu** [Odoo-mobile/framework#181]
Unable to connect to my server , the ProgressBar is always be shown

**Comment by YPerezM** [comment]
It is strange, when you write your url on the app doesnt appear any error? Can you select any of your databases?

I could enter by the app on my database using the option self-hosted URL

**Comment by jthanyu** [comment]
when I write my url on the app,the ProgressBar is always be shown,canot appear any error.

databases can't be shown

Whether the app relies on Google services ?

I can't connect to Google services

**Comment by EricHorvat** [comment]
I had a similar mistake, I import the framework and run it.
First, it asks for login info, shown the databases. But it crashes in Creating account.
I tried to open it again and crashes again.
I got in the errors and the more important part is 
```
06-13 12:17:51.793 7753-7753/com.rafaela E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
06-13 12:17:52.423 7753-7753/com.rafaela E/AndroidRuntime: FATAL EXCEPTION: main
                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rafaela/com.odoo.core.account.OdooLogin}: java.lang.SecurityException: caller uid 10183 is different than the authenticator's uid
```
I found that the problem could be the google service on the web

**Comment by EricHorvat** [comment]
I don't know how, I cleaned the emulator and phone up, and then I can logged in. 
But, I can't connect to the server, it shows no customers/providers/companies, but the ORM and Notes app does. With the AStudio monitor, notifies there in no network connection after the log in.

**Comment by dpr-odoo** [comment]
@jthanyu For progressbar always shown at login. Its fixed. 

and for @EricHorvat 

```
06-13 12:17:51.793 7753-7753/com.rafaela E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
06-13 12:17:52.423 7753-7753/com.rafaela E/AndroidRuntime: FATAL EXCEPTION: main
                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rafaela/com.odoo.core.account.OdooLogin}: java.lang.SecurityException: caller uid 10183 is different than the authenticator's uid

```

Its because, You have another application build with ``odoo mobile framework`` but installed from PlayStore or build on another system and installed on your device which share same user object.

Due to different build for application it says ``caller uid 10183 is different than the authenticator's uid``
