### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by YPerezM** [Odoo-mobile/framework#184]
I know there are a lot of issues about the sync, but I want to share what happen in my case. The sync used to work fine in the both ways (from server to device and device to server), but when I added three new columns on my ResPartner:
![captura de pantalla de 2016-06-09 10 55 01](https://cloud.githubusercontent.com/assets/8902208/15924234/598f8e1e-2e31-11e6-85e8-a4c8bee471b3.png)
 the sync does not work anymore from device to server. Only works from server to device. 

And depends of the number of these three columns I use, it happens differents things:

-If I use only one column(like in the image), the sync work perfectly in both ways.
-If I use two columns, the sync work fine on the customers,companies and suppliers (I am trying to add products, and the items that I enter on the device are deleted when I sync)
-In case I use the three columns, the sync only works from server to device (all items that I add on my device are deleted when I sync).

I am "new" on the Android development and I am trying to learn by myself, so any help or idea of what is going on will be useful. 
Thank you for the help

**Comment by dpr-odoo** [comment]
Closing.
