### ISSUE TITLE
Application Settings-->Sync data limit  issues

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#185]
first,set Sync data limit 1month old
then,let us sync data ,this data is 1month old
I set Sync data limit 2month old, then sync data again,but this data is not 2month old ,it is only 1month old data.
I think SharedPreferences's datas can not share other processes.

OPreferenceManager.java
modify 
 mPref = android.preference.PreferenceManager.getDefaultSharedPreferences(context);
to
mPref = context.getSharedPreferences("com.odoo_preferences", Context.MODE_MULTI_PROCESS);

Then fix it,  this modification is right or not ？
hi guys
If you have other idea, please tell me,thanks!!

**Comment by kasim1011** [comment]
Try this.
->  Open `OSyncAdapter.java` at `package com.odoo.core.service`.
->  Goto method name `syncData()` around line no. 170.
->  find statement `int data_limit = preferenceManager.getInt("sync_data_limit", 60);`
->  change that statement to `int data_limit = 360; // 12 months or 180 for 6 months`

See whether it works or not.

**Comment by mikedream89** [comment]
@kasim1011 
Yes, it works,thanks.
But i want to say the `android.preference.PreferenceManager.getDefaultSharedPreferences(context);` can not work on multi process.

**Comment by kasim1011** [comment]
@mikedream89 
It's my pleasure. you can close this issue if you are satisfied with my answer.
