### ISSUE TITLE
OdooConnector throws error BasicNetwork.performRequest: Unexpected responsoe code 502

### ISSUE THREAD

**Issue by warp10** [Odoo-mobile/framework#186]
I'm noticing errors in the sync process of a few model perfectly working up to yesterday. This error is thrown while the syncservice is running:

`06-13 10:08:03.802 it.openforce E/OdooConnector: [319] BasicNetwork.performRequest: Unexpected response code 502 for http://www.odoomobile.com/odoo_mobile/ping/dpWRwgrJAUE:APA91bFq-N9Jbtw10ziFIzvJBLZYAG1bS5ykaEImWH-a9wMZCJJXA-94eiLSRFlcEQqEw3-_OaBNNp1ZzipwP4rp8d_gj90dAqhF10irwU4Ihwf4RzHhfj-9M9IXL57aJcPKn6tEUiE2`

Then the syncservice is destroyed and records are not synced at all. I'm wondering if you might need any other data to understand where this error comes from, so I'll wait for your input about that.

**Comment by YPerezM** [comment]
I have just seen that in my log cat happens the same. Hope someone knows why that can happen, I have no idea

**Comment by warp10** [comment]
Thanks @YPerezM, so it looks like this issue is actually related to an error on odoomobile.com and impacting many of us.

Anyway, I'm wondering why the syncservice should request thing to odoomobile.com. Is that just a check to see if connection is alive (as the url might imply)?

**Comment by dpr-odoo** [comment]
@warp10 @YPerezM Fixed: https://github.com/Odoo-mobile/framework/commit/d7dd3d6da0ac597e28ae732345810cdaaf3a69aa
