### ISSUE TITLE
combine source code of available odoo mobile apps 

### ISSUE THREAD

**Issue by Mraimou** [Odoo-mobile/framework#187]
Hello,
I'm trying to create a new android app, I read the documentation and it is well written i really thank you for the great job.
I want to add "calendar" addon in "crm odoo mobile app" and messaging in "messaging odoo mobile app" to my app.
i tried and i got so many errors, i want to know if there is a right way to do this migration.
thank you.

**Comment by dpr-odoo** [comment]
Take copy of framework, and migrate each of the app features. Because each app has their own customization. You need to combine each feature separately.
