### ISSUE TITLE
NullPointerException raised when syncing some models

### ISSUE THREAD

**Issue by warp10** [Odoo-mobile/framework#189]
OMF raises a NullPointerException while syncing some models from our server (that is: project.task.type and project.issue). Other models on the same server are synced perfectly instead.

Steps to reproduce:
1- install the app on a clean emulator (or physical device)
2- login and create an account
3- go to sync settings and enable sync for the model you are interested in.

This is the traceback shown upon synchronization of project.issue:
```
06-21 12:14:32.169:sync_feeds I/OSyncService: Service created
06-21 12:14:32.175:sync_feeds I/OSyncAdapter: User        : admin[newdb]
06-21 12:14:32.175:sync_feeds I/OSyncAdapter: Model       : project.issue
06-21 12:14:32.175:sync_feeds I/OSyncAdapter: Database    : OdooSQLite_admin_newdb.db
06-21 12:14:32.175:sync_feeds I/OSyncAdapter: Odoo Version: 8.0
06-21 12:14:32.179:sync_feeds W/System.err: java.lang.NullPointerException
06-21 12:14:32.179:sync_feeds W/System.err:     at java.lang.Class.classForName(Native Method)
06-21 12:14:32.179:sync_feeds W/System.err:     at java.lang.Class.forName(Class.java:309)
06-21 12:14:32.179:sync_feeds W/System.err:     at java.lang.Class.forName(Class.java:273)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.OModel.get(OModel.java:493)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.setModel(BaseModelProvider.java:79)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:91)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentProvider.query(ContentProvider.java:966)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:478)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:422)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:669)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:661)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.OModel.getServerIds(OModel.java:625)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:152)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:136)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
06-21 12:14:32.179:sync_feeds W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.odoo.core.orm.OModel.getModelName()' on a null object reference
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:85)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:92)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentProvider.query(ContentProvider.java:966)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:478)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:422)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:669)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:661)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.orm.OModel.getServerIds(OModel.java:625)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:152)
06-21 12:14:32.179:sync_feeds W/System.err:     at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:136)
06-21 12:14:32.179:sync_feeds W/System.err:     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
06-21 12:14:32.181:sync_feeds I/OSyncService: Service destroyed
```

Here are the relevant pieces of code involved in the sync process (import's are omitted for the sake of brevity):

**Declarations in AndroidManifest.xml:**
```
<service
     android:name="com.odoo.addons.projects.services.ProjectIssueService"
     android:exported="true"
     android:process=":sync_feeds">
     <intent-filter>
        <action android:name="android.content.SyncAdapter" />
     </intent-filter>

     <meta-data
        android:name="android.content.SyncAdapter"
        android:resource="@xml/project_issue_sync_adapter" />
</service>

<provider
     android:name="com.odoo.addons.projects.providers.ProjectIssueProvider"
     android:authorities="com.odoo.addons.projects.project_issues"
     android:label="Project Issues"
     android:multiprocess="true" />
```

**app/src/main/java/com/odoo/addons/projects/providers/ProjectIssueProvider.java**
```
package com.odoo.addons.projects.providers;

public class ProjectIssueProvider extends BaseModelProvider {
    public static final String TAG = ProjectIssueProvider.class.getSimpleName();

    @Override
    public String authority() {
        return ProjectIssue.AUTHORITY;
    }
}
```

**app/src/main/java/com/odoo/addons/projects/services/ProjectIssueService.java**
```
package com.odoo.addons.projects.services;

public class ProjectIssueService extends OSyncService {
    public static final String TAG = ProjectIssueService.class.getSimpleName();

    @Override
    public OSyncAdapter getSyncAdapter(OSyncService service, Context context) {
        return new OSyncAdapter(getApplicationContext(), ProjectIssue.class, this, true);
    }

    @Override
    public void performDataSync(OSyncAdapter adapter, Bundle extras, OUser user) {
    }
}
```

**app/src/main/res/xml/project_issue_sync_adapter.xml**
```
<sync-adapter xmlns:android="http://schemas.android.com/apk/res/android"
    android:accountType="com.odoo.auth"
    android:contentAuthority="com.odoo.addons.projects.project_issues"
    android:supportsUploading="true"
    android:userVisible="true" />
```

**app/src/main/java/com/odoo/config/Addons.java**
```
package com.odoo.config;

public class Addons extends AddonsHelper {
    // other Addons here    
    OAddon issues = new OAddon(ProjectIssue.class);
}
```

**app/src/main/java/com/odoo/addons/projects/models/ProjectIssue.java**
```
package com.odoo.addons.projects.models;

public class ProjectIssue extends OModel {
    public static final String TAG = ProjectIssue.class.getSimpleName();
    public static final String AUTHORITY = "com.odoo.addons.projects.project_issues";

    OColumn name = new OColumn("Issue", OVarchar.class);
    OColumn project_id = new OColumn("Project", ProjectProject.class, OColumn.RelationType.ManyToOne);
    OColumn description = new OColumn("Private Note", OText.class);
    OColumn user_id = new OColumn("Assigned to", ResUsers.class, OColumn.RelationType.ManyToOne);
    OColumn stage_id = new OColumn("Stage", ProjectTaskType.class, OColumn.RelationType.ManyToOne);

    public ProjectIssue(Context context, OUser user) {
        super(context, "project.issue", user);

        setHasMailChatter(true);
    }

    @Override
    public Uri uri() {
        return buildURI(AUTHORITY);
    }
}
```

**Comment by kasim1011** [comment]
@warp10 facing the same issue. There's no perticular message. also, Exception is coming from `odoo-rpc-v3` `aar`.

**Comment by dpr-odoo** [comment]
@warp10 

First thing, You have to register Class with parent of ``BaseFragment`` in ``Addons`` class. In you code, you have declared Model class ``ProjectIssue`` 

Refer creating addon: http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/addons.html

In error, It shows that model for you project issues not found at runtime, because your models are not actually registered in ORM due to Invalid Addon class you have provided in ``Addons`` 

```java
public class Addons extends AddonsHelper {
    // other Addons here    
    OAddon issues = new OAddon(ProjectIssue.class);
}
```
Your model ``ProjectIssue`` will be in ``database()`` method of your ``Addon`` class.
 http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/addons.html#database

**Comment by warp10** [comment]
@dpr-odoo thanks a lot for your thorough answer, and sorry for the noise: indeed the missing Class inheriting baseFragment was the cause of this issue. I'm hence closing this bug.

**Comment by alejandro2112** [comment]
present the same problem:
07-04 16:59:49.169 26926-26954/com.example:sync_product W/System.err: java.lang.NullPointerException: name == null
07-04 16:59:49.174 26926-26954/com.example:sync_product W/System.err:     at java.lang.Class.classForName(Native Method)
07-04 16:59:49.174 26926-26954/com.example:sync_product W/System.err:     at java.lang.Class.forName(Class.java:217)
07-04 16:59:49.174 26926-26954/com.example:sync_product W/System.err:     at java.lang.Class.forName(Class.java:172)
07-04 16:59:49.174 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.OModel.get(OModel.java:129)
07-04 16:59:49.174 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.setModel(BaseModelProvider.java:79)
07-04 16:59:49.174 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:91)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentProvider.query(ContentProvider.java:673)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentProvider$Transport.query(ContentProvider.java:210)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:375)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:318)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:650)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:642)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.OModel.getServerIds(OModel.java:606)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:220)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:204)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err: java.lang.NullPointerException
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:85)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:92)
07-04 16:59:49.179 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentProvider.query(ContentProvider.java:673)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentProvider$Transport.query(ContentProvider.java:210)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:375)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:318)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:650)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:642)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.orm.OModel.getServerIds(OModel.java:606)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:220)
07-04 16:59:49.184 26926-26954/com.example:sync_product W/System.err:     at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:204)
07-04 16:59:49.189 26926-26954/com.example:sync_product W/System.err:     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
07-04 16:59:49.209 26926-26926/com.example:sync_product I/OSyncService: Service destroyed
07-04 17:00:03.099 26048-26146/com.example I/global: call createSocket() return a new socket.
