### ISSUE TITLE
OFileManager should allow to take picture with higher resolution

### ISSUE THREAD

**Issue by warp10** [Odoo-mobile/framework#192]
OFileManager does a great job with regard to taking pictures and handling data from camera, nevertheless it looks like it's always started with a poor resolution. 
There should options to configure the resolution and quality either programmatically or via user interface by the user him/her-self.

**Comment by 74n3r** [comment]
i also researching this.. how was done ?

**Comment by warp10** [comment]
I tried to dig into the code of OMF, but couldn't find anything that could help me set the quality of the picture. Curiously, on a physical device I could set the camera to shot at full 5MP, but still I get a disappointing 500x375 base64 encoded image when the Activity issued by FileManager returns. I really hope @dpr-odoo can help us here, otherwise I guess the only option available is to use the standard Android camera API and do everything else by hand (which is sorrowful, OFileManager is really great, as I already said)

**Comment by dpr-odoo** [comment]
@warp10 

Fixed: https://github.com/Odoo-mobile/framework/commit/1e164be9eb27f64af4774a10089409b9063f3bfc

Added Request Types:
 - RequestType.CAPTURE_HIGH_IMAGE
 - RequestType.IMAGE_OR_CAPTURE_HIGH_IMAGE

**Comment by warp10** [comment]
@dpr-odoo Just great, it works like a charm. Thanks a lot!
