### ISSUE TITLE
Camera permissions are granted by user but not saved into Android 6

### ISSUE THREAD

**Issue by warp10** [Odoo-mobile/framework#198]
Disclaimer: I'm still using the build 5 of version 2.1.0alpha + backport of commit 1e164be9, so please ignore and close this bug if this has been already fixed in a later version.

I get an error about camera permissions using OFileManager with targetSdkVersion = 23 on Android 6, despite the user actually granted permission.

Steps to reproduce:
- Issue a camera request via OFileManager (see the code snippet below)
- The user is asked to grant permission for camera and accept it
- The app crashes because camera permissions are not available

If after all that I go to app settings -> permissions, the camera permissions is turned off. If I turn it on manually, then the app works fine.

I'm wondering if something else is expected on my side to save the granted permission. In that case, I'd be happy to get more info about that.

PS: The code I'm currently using to request the camera is:
```OFileManager fileManager = new OFileManager(this);
fileManager.requestForFile(OFileManager.RequestType.CAPTURE_HIGH_IMAGE);```

**Comment by dpr-odoo** [comment]
@warp10 

Its taking only ``WRITE_EXTERNAL_STORAGE`` permission. 
It fixed in ``OFileManager`` for ``CAMERA`` permission. https://github.com/Odoo-mobile/framework/commit/4511acb1b9f2f0349ffe3b70c31b2d55c2fd069a

**Comment by warp10** [comment]
Great work @dpr-odoo, and thank you for your prompt patch. It works like a charm now, hence closing tihs bug
