### ISSUE TITLE
get user id error

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#199]
hi guys:
         login in two users ondevice, User admin and test.
         now test login in online on device.
         when i run
`OArguments loc = new OArguments();
        loc.add(new JSONObject());`
 `mOdoo.callMethod("a.model", "getDatas", loc, null)`

this is andmin's ID in context not test ID, why?
the code's file is OdooWrapper.clss ,method is callMethod

`   private void callMethod(String model, String method, OArguments arguments, HashMap<String,
Object> kwargs, HashMap<String, Object> context, IOdooResponse callback, OdooSyncResponse 
backResponse) {

```
    String url = this.serverURL + "/web/dataset/call_kw";

    try {
        JSONObject e = new JSONObject();
        e.put("model", model);
        e.put("method", method);
        e.put("args", arguments.getArray());
        e.put("kwargs", kwargs != null?new JSONObject(this.gson.toJson(kwargs)):new JSONObject());
        e.put("context", context != null?new JSONObject(this.gson.toJson(this.updateContext(context))):this.odooSession.getUserContext());
        this.newJSONPOSTRequest(url, e, callback, backResponse);
    } catch (Exception var10) {
        OdooLog.e(var10, new Object[]{var10.getMessage()});
    }

}`
```
- if context not null, and context = {"uid":4}, `this.updateContext(context)`  return {"uid":1,"lang":"en_US","tz":"Asia/Shanghai"}
- if context is null , `this.updateContext(context)`  also return {"uid":1,"lang":"en_US","tz":"Asia/Shanghai"} 

@kasim1011

**Comment by mikedream89** [comment]
hi guys, who can help me? thanks

**Comment by kasim1011** [comment]
I can't understand, please add some logs and describe your issue more specifically.

**Comment by mikedream89** [comment]
![22](https://cloud.githubusercontent.com/assets/11469375/16982231/638c06c8-4ea1-11e6-8a44-bbee20200fa7.png)

![33](https://cloud.githubusercontent.com/assets/11469375/16982354/de83525a-4ea1-11e6-8724-1759c7f1d088.png)

Login user id is 4, but this here get 1.

**Comment by mikedream89** [comment]
hi:
   Do you hava any idea?

**Comment by mikedream89** [comment]
@kasim1011 
Do you understand my mean?  If you hava understanded , could you hava idea about the issue? 
Thanks very much!

**Comment by kasim1011** [comment]
@mikedream89 no man!

**Comment by mikedream89** [comment]
@dpr-odoo 
Do you know my mean?
Could you help me? Thanks

**Comment by tonysumi** [comment]
those are the local _id and server id

**Comment by dpr-odoo** [comment]
Closing issue. If not fixed please reopen.
