### ISSUE TITLE
How prohibited odoo's account login on device.

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#200]
hi guys , 
I do not want to login by odoo's account.
How to do?

**Comment by warp10** [comment]
Tap on "Add self-hosted URL", then enter your URL and login details

**Comment by mikedream89** [comment]
@warp10 
I mean is when device connectd atabase of myself , but it can also login in by odoo's account.
Now i want to forbid the odoo's account .

**Comment by warp10** [comment]
I guess you need to edit the layout for OdooLogin e remove the TextView, no idea if other means are available

**Comment by mikedream89** [comment]
![qq 20160725095948](https://cloud.githubusercontent.com/assets/11469375/17088498/917fb808-524e-11e6-8810-84a96abf3f84.png)

hi @warp10 , i remove the TextView ,but it also can login in with "Add self-hosted URL", if i put "www.odoo.com" in TextView.

**Comment by warp10** [comment]
How about not putting www.odoo.com in that form? :)

**Comment by mikedream89** [comment]
Not put www.odoo.com can solve my question.But i think it is not the best solution.

**Comment by tonysumi** [comment]
In OdooLogin.java , I changed the domain like this 

 private void loginUser() {
        Log.v("", "LoginUser()");
        StringBuilder domain=new StringBuilder();
        domain.append("https://");
        domain.append(edtSelfHosted.getText().toString());
        domain.append(".something.com");
        String serverURL =domain.toString();
        /*createServerURL((mSelfHostedURL) ? edtSelfHosted.getText().toString() :
                OConstants.URL_ODOO);*/ 

with this, now i'm able to restrict other domains and login to my instance only.

**Comment by dpr-odoo** [comment]
@mikedream89 

Remove https://github.com/Odoo-mobile/framework/blob/master/app/src/main/res/layout/base_login.xml#L232-L243 and its logic

Add default your server url to https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/datas/OConstants.java#L23 

Replace with ``OConstant.URL_ODOO`` only. https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/account/OdooLogin.java#L196-L197

It will always login to your server only.
