### ISSUE TITLE
Sync data very slowly, how to do? 

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#205]
hi,
   when i sync several tables, it very slowly, about 4000 rows. how to do?

**Comment by mikedream89** [comment]
i think it because too many  `ManyToOne` in model.
Anybody has any ideas？

**Comment by dpr-odoo** [comment]
Limit the data with ``syncDataLimit()`` in sync service http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/addons.html?highlight=syncadapter#sync-service-class . Because with huge data it make it slow to process.
