### ISSUE TITLE
Not able to update.

### ISSUE THREAD

**Issue by tonysumi** [Odoo-mobile/framework#208]
Hi Everyone,

I've been trying to update the phone number field of a customer but It's not working.
The changes made is saved in local db only. No changes can be seen on sever side.

 case R.id.menu_profile_save:
                OValues values = res_partnerFrom_edit.getValues();
                Log.d("TAG","values-------"+values);
                if (values != null) {
                    if (userDatas != null) {
                        ResPartner partner = new ResPartner(getApplicationContext(), null);
                        partner.update(165, values);

Note: 165 is the hardcoded value for record.getInt(OColumn.ROW_ID)
Anyone? any idea?

**Comment by dpr-odoo** [comment]
@tonysumi can you check with latest update. I'm closing issue. If it's not solved please reopen it. Thanks
