### ISSUE TITLE
Users share the same database.

### ISSUE THREAD

**Issue by r-mckay** [Odoo-mobile/framework#210]
Hello,

It appeared during my developments that two different users could share the same database, instead of having each one their own as explained here : http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/directory-structure.html

The steps to reproduce this behaviour are with a self-hosted server :
    - clean install the application;
    - login with an account;
    - after a moment, logout;
    - from the login screen, login with an other account.

For this second login, in the logs, the OSyncAdapter correctly displays the user and the model. But the database is corresponding to the first created user.

> I/OSyncAdapter: User        : "second user"
> I/OSyncAdapter: Model       : res.partner
> I/OSyncAdapter: Database    : "first user's database"
> I/OSyncAdapter: Odoo Version: 8.0
> V/OSyncAdapter: Sync for ...

For the moment, I use a test in the OModel.java constructor which tests if there is an existing static sqlite or not, and if it belongs to the current user or not.
I could send a PR if this is the best way to solve this.

Does anyone reproduce this behaviour?

Thanks.

**Comment by kasim1011** [comment]
@r-mckay 
@dpr-odoo 

See this https://github.com/Odoo-mobile/framework/issues/194. Please close the issue if this works for you.
