### ISSUE TITLE
how to call the method (def process(self))

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#215]
hi guys:
 how to call  the method 

>     @api.multi
    def process(self):
        self.ensure_one()
        self._process()

**Comment by dpr-odoo** [comment]
@mikedream89 

You can call from your model object for example:

```java
ResPartner partner = new ResPartner(context,null);
OArguments args = new OArguments(); // Pass your arguments
Object result = partner.getServerDataHelper().callMethod("process", args);
````

**Comment by mikedream89** [comment]
@dpr-odoo 
i use getServerDataHelper().callMethod("process", args);
it will error, for this:


> 2016-09-08 07:24:27,999 8 ERROR odoo9_test3 openerp.http: Exception during JSON request handling.
odoo9_1 | Traceback (most recent call last):
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 643, in _handle_exception
odoo9_1 |     return super(JsonRequest, self)._handle_exception(exception)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 680, in dispatch
odoo9_1 |     result = self._call_function(**self.params)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 316, in _call_function
odoo9_1 |     return checked_call(self.db, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/service/model.py", line 118, in wrapper
odoo9_1 |     return f(dbname, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 309, in checked_call
odoo9_1 |     result = self.endpoint(*a, **kw)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 959, in __call__
odoo9_1 |     return self.method(*args, **kw)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 509, in response_wrap
odoo9_1 |     response = f(*args, **kw)
odoo9_1 |   File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 893, in call_kw
odoo9_1 |     return self._call_kw(model, method, args, kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 885, in _call_kw
odoo9_1 |     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/api.py", line 250, in wrapper
odoo9_1 |     return old_api(self, *args, **kwargs)
odoo9_1 | TypeError: old_api() takes at least 4 arguments (3 given)

**Comment by dpr-odoo** [comment]
@mikedream89 

Your method have arguments and I think you are not passing it in `OArguments`

**Comment by mikedream89** [comment]
@dpr-odoo 
 this is my code
>  @api.multi
    def process(self):
        self.ensure_one()
        self._process()

> OArguments loc = new OArguments();
                    return (Boolean) getServerDataHelper().callMethod("process",loc);

**Comment by dpr-odoo** [comment]
Try with adding default empty array `args.add(new ArrayList<Integer>());` Because python method required one parameter to be valid ids list (which missing in your request **takes at least 4 arguments (3 given)**)

Here example:

```java
ResPartner partner = new ResPartner(context,null);
OArguments args = new OArguments(); // Pass your arguments
args.add(new ArrayList<Integer>());
Object result = partner.getServerDataHelper().callMethod("process", args);
```

**Comment by mikedream89** [comment]
@dpr-odoo 

>    WHERE "stock_backorder_confirmation".id IN ('[]')  ORDER BY "stock_backorder_confirmation"."id"  
odoo9_1 |                     
odoo9_1 | 2016-09-08 09:52:01,577 8 ERROR odoo9_test3 openerp.http: Exception during JSON request handling.
odoo9_1 | Traceback (most recent call last):
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 643, in _handle_exception
odoo9_1 |     return super(JsonRequest, self)._handle_exception(exception)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 680, in dispatch
odoo9_1 |     result = self._call_function(**self.params)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 316, in _call_function
odoo9_1 |     return checked_call(self.db, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/service/model.py", line 118, in wrapper
odoo9_1 |     return f(dbname, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 309, in checked_call
odoo9_1 |     result = self.endpoint(*a, **kw)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 959, in __call__
odoo9_1 |     return self.method(*args, **kw)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/http.py", line 509, in response_wrap
odoo9_1 |     response = f(*args, **kw)
odoo9_1 |   File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 893, in call_kw
odoo9_1 |     return self._call_kw(model, method, args, kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 885, in _call_kw
odoo9_1 |     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/api.py", line 250, in wrapper
odoo9_1 |     return old_api(self, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/api.py", line 381, in old_api
odoo9_1 |     result = method(recs, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/addons/stock/wizard/stock_backorder_confirmation.py", line 38, in process
odoo9_1 |     self._process()
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/api.py", line 248, in wrapper
odoo9_1 |     return new_api(self, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/addons/stock/wizard/stock_backorder_confirmation.py", line 24, in _process
odoo9_1 |     for pack in self.pick_id.pack_operation_ids:
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/fields.py", line 828, in __get__
odoo9_1 |     self.determine_value(record)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/fields.py", line 926, in determine_value
odoo9_1 |     record._prefetch_field(self)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/api.py", line 248, in wrapper
odoo9_1 |     return new_api(self, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/models.py", line 3283, in _prefetch_field
odoo9_1 |     result = records.read([f.name for f in fs], load='_classic_write')
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/api.py", line 248, in wrapper
odoo9_1 |     return new_api(self, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/models.py", line 3213, in read
odoo9_1 |     self._read_from_database(stored, inherited)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/api.py", line 248, in wrapper
odoo9_1 |     return new_api(self, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/models.py", line 3351, in _read_from_database
odoo9_1 |     cr.execute(query_str, params)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/sql_db.py", line 141, in wrapper
odoo9_1 |     return f(self, *args, **kwargs)
odoo9_1 |   File "/opt/odoo/sources/odoo/openerp/sql_db.py", line 220, in execute
odoo9_1 |     res = self._obj.execute(query, params)
odoo9_1 | DataError: invalid input syntax for integer: "[]"
odoo9_1 | LINE 2: ...      WHERE "stock_backorder_confirmation".id IN ('[]')  ORD...
odoo9_1 |                                                              ^
odoo9_1 |

**Comment by mikedream89** [comment]
hi guys：
 Who can give me any ideas about this bug？

**Comment by mikedream89** [comment]
@dpr-odoo @warp10 @sla-odoo @r-mckay @mga-odoo 

Who can help me about this issue? thanks

**Comment by mikedream89** [comment]
fix it.this is my code:

> ResPartner partner = new ResPartner(context,null);
OArguments args = new OArguments(); // Pass your arguments
args.add(new JSONArray());
Object result = partner.getServerDataHelper().callMethod("process", args);
