### ISSUE TITLE
RPC_REQUEST_TIME_OUT > 30s not taken in account (capped at 30s)

### ISSUE THREAD

**Issue by r-mckay** [Odoo-mobile/framework#217]
Hello!

We do not achieve to change the requests timeout to a value greater than 30 seconds.
We localized the RPC_REQUEST_TIME_OUT constant in OConstants.java and changed its value. The behaviour is correct when the value is under 30000 ms, but when it's greater, it seems to be locked at 30000 ms.

Is it possible to set a timeout greater than 30000ms ? Are we missing something?

Thanks!

**Comment by mikedream89** [comment]
Same issue #229

**Comment by mikedream89** [comment]
@r-mckay 
Are you any ideas about this problem now?

**Comment by r-mckay** [comment]
Hello.
Yes. We think that this is related to the default retry policy of the requests sent through the odoo-rpc-v3 AAR file. Its source code is needed to fully understand and test any fix. This code is as far as I know not available yet. (#222)

**Comment by dpr-odoo** [comment]
OConstants.RPC_REQUEST_TIME_OUT and  OConstants.RPC_REQUEST_RETRIES is now working.

If you are calling direct library method use ``withRetryPolicy()`` before calling server method

``` java
Integer timeout = 5000; // Miliseconds
Integer retry = 1; // Number of retries

odooObject.withRetryPolicy(timeout, retry).callMethod("res.partner",....
```
