### ISSUE TITLE
Objects synced from a relation are not completely populated.

### ISSUE THREAD

**Issue by r-mckay** [Odoo-mobile/framework#218]
There seems to be an issue with the sync of the relations of parent objects.
These children objects are not completely populated and the query shows a curious behaviour with the "id in" and the "id not in".

> "domain":[["id","in",[1939,409,1953,5123,1950,1511]],"|",["create_date",">=","2015-09-18 00:00:00"],["id","not in",[1511,1939,409,5123,1950,1953]]]

**Comment by dpr-odoo** [comment]
Merged.
