### ISSUE TITLE
 odoo-rpc-v3 source code

### ISSUE THREAD

**Issue by r-mckay** [Odoo-mobile/framework#222]
Hello!

We are unable to find the source code of the odoo-rpc-v3.aar archive.
Can you provide us a link to this code?

Thank you in advance!

**Comment by r-mckay** [comment]
Hi @dpr-odoo @asa-odoo !
Can we have your feedback on this please?
Thank you!

**Comment by mikedream89** [comment]
why no feedback about this?

**Comment by r-mckay** [comment]
Hello @dpr-odoo @asa-odoo.
Can we have your feedback on this please? The project is as far as I know still not compliant with its license, and having this source code available would be very useful.
Are you considering this, will you work on it, maybe it already is a work in progress?
Thank you in advance.

**Comment by r-mckay** [comment]
The odoo-rpc-v3 archive is now opened since 194303651a82cd5b0732f3529ea370e893ef8147
Thank you.
