### ISSUE TITLE
How to get all the records from server

### ISSUE THREAD

**Issue by adam-nadar** [Odoo-mobile/framework#224]
i got some helper tables with ManyToOne relationship
how can i get all the records from the server not just only the dependent records...
adding that table to baseModels doesn't helps.....

**Comment by asa-odoo** [comment]
@adam-nadar 
follow the steps from Odoo docs. may it helps you.
http://odoo-mobile-doc.readthedocs.io/en/latest/getting-started/working-with-odoo-mobile/components/addons.html

**Comment by adam-nadar** [comment]
sir actually itz fetchin the data..
n I hav done all the procedure mentioned in the official documentation
if I'm creating a new record the field which is ManyToone are no listed if the previous fetched record doesn't have the relation

**how can i get all the records from the server not just only the dependent records...**

**Comment by dpr-odoo** [comment]
@adam-nadar 

You can pass chain sync model when you main model sync finished in ``OSyncService`` https://github.com/Odoo-mobile/crm/blob/master/app/src/main/java/com/odoo/addons/crm/services/CRMLeadSyncService.java#L61-L72

By calling ``adapter.onSyncFinish(this)`` it will implement ``ISyncFinishListener`` and there you can pass your model sync object https://github.com/Odoo-mobile/crm/blob/master/app/src/main/java/com/odoo/addons/crm/services/CRMLeadSyncService.java#L67-L71
