### ISSUE TITLE
When i call odoo methed， it  odoo's methed be called 2 times?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#229]
hi:
When i call odoo methed， it  odoo's methed be called 2 times? why?

**Comment by mikedream89** [comment]
i change this RPC_REQUEST_TIME_OUT no working ? why

**Comment by mikedream89** [comment]
@dpr-odoo

**Comment by mikedream89** [comment]
@kasim1011 
Can you help me? do you know this problem?

**Comment by kasim1011** [comment]
@mikedream89 
@dpr-odoo 

I had face some problem similar to this. In my case it was server function call using `AsyncTask` on button click. but, server call automatically get call in Activity's onCreate(). I don't why this get done automatically. than I've put some `Logs` on button click but, `Logs` was never print because button was never pressed but still server call get done automatically Than finally I've solve this using `SharedPreference` boolean flag. on button click I set the my boolean flag true. inside `AsyncTask` I've put check on all of 3 Method on `preExecute`, `doInBackground`, `postExecute`. Now, when I start Activity My AsyncTask always catch automatic call in preExcecute method. that saved my life. yes, Don't forget stop `AsyncTask` using `cancel(true);` on automatic call.

Hope this will help you somehow.

**Comment by mikedream89** [comment]
@kasim1011 

I think `RPC_REQUEST_TIME_OUT`  mean is when i first request until after 10 seconds (RPC_REQUEST_TIME_OUT) it will second request automatically. But when i modify `RPC_REQUEST_TIME_OUT` to 60 seconds, it also 10 seconds twice requested。
I do not konw ,why i modify the value no working.

**Comment by kasim1011** [comment]
@mikedream89 

can you give me some code snippet where you're modifying this value (inside Activity, Fragment or BaseFragment). how you're modifying value (Syntax) & When You're modifying (on which event). so that we can have deeper look onto this.

**Comment by mikedream89** [comment]
@kasim1011 
this is debug image：
![1](https://cloud.githubusercontent.com/assets/11469375/18827948/0a679250-8408-11e6-9908-8f7da3a2c90b.png)
this is odoo method be called log
![2](https://cloud.githubusercontent.com/assets/11469375/18827968/2415fb06-8408-11e6-85e2-3131252a3659.png)

this is my code:  app/src/main/java/com/odoo/datas/OConstants.java
![3](https://cloud.githubusercontent.com/assets/11469375/18827974/2d500ae0-8408-11e6-994c-7770d9c49081.png)

**Comment by mikedream89** [comment]
@kasim1011 
by the way, do you have odoo-rpc-v3.aar code?

**Comment by kasim1011** [comment]
@mikedream89 
I'm looking on your issue. about odoo-rpc-v3.aar code. you can always decompile AAR into Android-studio project.

**Comment by mikedream89** [comment]
@kasim1011 
ok , let me try to decompile AAR into Android-studio project, and you can go to looking on my issue. :) thanks :)

**Comment by r-mckay** [comment]
Hello,
concerning the aar source code, there is an opened issue here : [https://github.com/Odoo-mobile/framework/issues/222](url)
There is no answer from the Odoo team yet.

**Comment by mikedream89** [comment]
@r-mckay 
i cannot open the url https://github.com/Odoo-mobile/framework/issues/222

**Comment by mikedream89** [comment]
@r-mckay  
thanks

**Comment by mikedream89** [comment]
@kasim1011 
There is no progress?

**Comment by kasim1011** [comment]
@mikedream89 
Here's what I've done far. [here](https://github.com/kasim1011/odoo-rpc-v3)

Do not use this for production or commercial use. This is just for studying the code...

**Comment by mikedream89** [comment]
@kasim1011 
 thanks for your code， but this code can not improt to project to run.

**Comment by kasim1011** [comment]
@mikedream89 
yes, The [decompiler](http://jd.benow.ca) which I've used for this doesn't 100% decompile the code.
But. Still we can get most out of it.

**Comment by mikedream89** [comment]
@dpr-odoo

'  try {

                        IOdooResponse e = OdooWrapper.this.responseQueue.get(postData.getInt("id"));
                        if(e != null) {
                            e.onError(odooError);
                            OdooWrapper.this.responseQueue.remove(postData.getInt("id"));
                        }
                    } catch (JSONException var6) {
                        OdooLog.e(var6, new Object[]{var6.getMessage()});
                    }

                }
            };
            JsonObjectRequest e = new JsonObjectRequest(url, postData, this, request);
            e.setRetryPolicy(new DefaultRetryPolicy(Odoo.REQUEST_TIMEOUT_MS.intValue(), Odoo.DEFAULT_MAX_RETRIES.intValue(), 1.0F));
            this.requestQueue.add(e);
        } else {
            JsonObjectRequest request1 = new JsonObjectRequest(url, postData, requestFuture, requestFuture);

           // why not add this code ???????
          // request1.setRetryPolicy(new DefaultRetryPolicy(Odoo.REQUEST_TIMEOUT_MS.intValue(), Odoo.DEFAULT_MAX_RETRIES.intValue(), 1.0F));
          // 

            this.requestQueue.add(request1);

            try {
                OdooResponse e1 = this.parseToResponse((JSONObject)requestFuture.get((long)Odoo.REQUEST_TIMEOUT_MS.intValue(), TimeUnit.MILLISECONDS));
                backResponse.setResponse(e1);
            } catch (Exception var9) {
                OdooLog.e(var9, new Object[0]);
            }
        }'

**Comment by dpr-odoo** [comment]
Use ``withRetryPolicy()`` before calling server method

``` java
Integer timeout = 5000; // Miliseconds
Integer retry = 1; // Number of retries

odooObject.withRetryPolicy(timeout, retry).callMethod("res.partner",....
```

**Comment by mikedream89** [comment]
hi @dpr-odoo 
When i set timeout =60000;  the app has stopped and print error loger is : 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String odoo.helper.utils.gson.OdooResult.toString()' on a null object reference

How long can the maximum timeout be set?

Thanks @dpr-odoo

**Comment by dpr-odoo** [comment]
@mikedream89 

There is no limit of setting timeout. But it may possible that your server timeout setting giving timeout error  before 60000.

I have tested it with 60000 and its work fine when server is busy for 60s. But before testing that i have changed some configuration in ngnix and odoo timeout.

Ngnix  ``proxy_read_timeout``
Odoo `` --limit-time-real``
Android Odoo request timeout

It will consider minimum timeout from these three settings.

**Comment by mikedream89** [comment]
Thanks @dpr-odoo  
I will try

**Comment by mikedream89** [comment]
@dpr-odoo 
`--limit-time-real` suport odoo7 ?

**Comment by dpr-odoo** [comment]
@mikedream89 yes Odoo 7 supports ``--limit-time-real`` https://github.com/odoo/odoo/blob/7.0/openerp/tools/config.py#L294-L296

You can check available commands by running ``./openerp-server --help``
