### ISSUE TITLE
Documentation for lib/odoo-v2.jar

### ISSUE THREAD

**Issue by h4k1m0u** [Odoo-mobile/framework#23]
Can you please tell me where I can find the documentation for lib/odoo-v2.jar.

**Comment by maitsapo** [comment]
Has anyone received documentation yet?

**Comment by sjpatel21** [comment]
I have lost all the hopes.

**Comment by jzahid** [comment]
Hi ,
Version 2 is not yet stable, do not rely on developpers to help you for documentation. I think it will be released once this version is stable.
So, help yourself and help the community. It's not dificult to browse and understand the code. the simple app , is built for that purpose. 
You can help, for example write some explication comments in the code and request a pull, or maybe do the first step, write a small doc intro in the wiki, i think owners of this repo won't mind. Once you start , others will follow.

**Comment by maitsapo** [comment]
Great advise. We just cant be consumers i suppose. Thanx.

**Comment by lakshman12345** [comment]
is there any documentation on odoo-v2.jar
