### ISSUE TITLE
Update build.gradle in intro-slider-lib AND Provide intro-slider-lib module as AAR.

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#234]
The `build.gradle` file in `intro-slider-lib` module has get outdated so, consider to update it like following.

	apply plugin: 'com.android.library'

	android {
		compileSdkVersion 24
		buildToolsVersion "24.0.3"

		defaultConfig {
			minSdkVersion 9
			targetSdkVersion 24
		}

		buildTypes {
			release {
				minifyEnabled false
				proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
			}
		}
	}

	dependencies {
		compile 'com.android.support:support-v4:24.2.1'
	}

Provide the `intro-slider-lib` module as `AAR` format if possible as it will be more structured or you can directly merge `intro-slider-lib` module directly into `app` module.

Thanks in advance
@dpr-odoo and entire `odoo-mobile` community.

**Comment by r-mckay** [comment]
Hi!
I take the liberty to add a point here.
If the `intro-slider-lib` becomes an AAR, its source code must then be available to keep the project compliant with its AGPL v3 license. We currently have an issue concerning the odoo-rpc-v3 AAR (#222) that has no source code available (unless I am mistaken).
Thanks!

**Comment by kasim1011** [comment]
@r-mckay 

so, we can merge this module into `app` module inside package name (let's say) `slider`.
