### ISSUE TITLE
[SUGGESTION] Use Retrofit instead of volley

### ISSUE THREAD

**Issue by talazoft** [Odoo-mobile/framework#235]
Hello dev team :)

Just want to give you suggestion, why not using Retrofit as HTTP client. It's faster and uses less resources. I know all of you devs is busy, but it's worth to consider.

http://instructure.github.io/blog/2013/12/09/volley-vs-retrofit/

**Comment by kalvian1060** [comment]
dou you have example framework odoo with retrofit???

**Comment by talazoft** [comment]
No I don't, the http client is compiled inside odoo-rpc-v3, and there is no source code provided

**Comment by r-mckay** [comment]
Hello, concerning the odoo-rpc-v3, there already is an issue asking for its source code. Please see #222. Thanks!

**Comment by dpr-odoo** [comment]
odoo-rpc-v3 source merged with framework https://github.com/Odoo-mobile/framework/commit/194303651a82cd5b0732f3529ea370e893ef8147
