### ISSUE TITLE
Sync is not working on Odoo.com or SaaS or Self-hosted URL.

### ISSUE THREAD

**Issue by berpweb** [Odoo-mobile/framework#236]
Steps to reproduce:
1) Clone the framework (https://github.com/Odoo-mobile/framework)
2) Launch the app in Emulator, login and try to sync. Customer sync is not working.
3) Now Build the framework to APK. Build Variant "release" in android studio 2.2.1.
4) Generate the signed APK.
5) Install in Mobile.
6) I can able to Login successfully.
7) Customer created in Odoo stays there and Customer created in Mobile App stays there itself, which is not synced with one another.
8) I have changed the sync value to every 5 minutes and data limit to 12 months and have been tried the sync now. Nothing works.

I have been tested this on Samsung Galaxy On8, Asus Zenfone 2 real mobiles and Nexus 5 on the emulator.

Data sync not working on the emulator also.

Tested with Odoo.com, Self hosted and SaaS platform with 10.0E, 9.0E, 8.0C

**Comment by prie** [comment]
it happen to me too.

**Comment by ghozimahdi** [comment]
maybe you less tawakal
