### ISSUE TITLE
 Request timed out how to solve?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#242]
HI
`callMethod`   Request timed out how to solve?

**Comment by mikedream89** [comment]
com.android.volley.TimeoutError

**Comment by mikedream89** [comment]
@dpr-odoo  @sla-odoo 
Could you give me any idea？

**Comment by dpr-odoo** [comment]
OConstants.RPC_REQUEST_TIME_OUT and  OConstants.RPC_REQUEST_RETRIES is now working.

If you are calling direct library method use ``withRetryPolicy()`` before calling server method

``` java
Integer timeout = 5000; // Miliseconds
Integer retry = 1; // Number of retries

odooObject.withRetryPolicy(timeout, retry).callMethod("res.partner",....
```
