### ISSUE TITLE
odoo-rpc-v3 source code? 

### ISSUE THREAD

**Issue by purevsurento** [Odoo-mobile/framework#247]
Hello!

We are unable to find the source code of the odoo-rpc-v3.aar archive.
Can you provide us a link to this code?

Thank you in advance!

**Comment by mikedream89** [comment]
hi @purevsurento 
please look at #222  about odoo-rpc-v3 source code

**Comment by kasim1011** [comment]
hi @purevsurento  @mikedream89 plz, look at my [sample](https://github.com/kasim1011/odoo_jsonrpc_javase_eclipse).

**Comment by r-mckay** [comment]
The archive is opened since 194303651a82cd5b0732f3529ea370e893ef8147
