### ISSUE TITLE
Odoo Instant Chat Messaging Feature source code

### ISSUE THREAD

**Issue by naitikvithlani** [Odoo-mobile/framework#250]
Hello Everyone !!!!

Hope you all doing good in odoo-mobile.

I want to implement or develop chatting feature same as odoo web.

Is there any ready made project or library for it to take reference from it.

Thanks in advance.

**Comment by dpr-odoo** [comment]
You can refer old messaging (Instant Messaging) app which support 7.0 and 8.0 for reference (Not updated so long but you can refer it for model integration). https://github.com/Odoo-mobile/messaging

There is developer documentation available for creating apps with Odoo Mobile framework http://odoomobile.com/page/get-started

**Comment by naitikvithlani** [comment]
@dpr-odoo I have created this kind of feature with framework application of odoo.

Thank you.
