### ISSUE TITLE
java.lang.ClassCastException: java.util.HashMap cannot be cast to com.odoo.core.rpc.helper.ORecordValues

### ISSUE THREAD

**Issue by purevsurento** [Odoo-mobile/framework#263]
sale.getServerDataHelper().updateOnServer((ORecordValues) data, record.getInt("id"));

To error:

java.lang.ClassCastException: java.util.HashMap cannot be cast to com.odoo.core.rpc.helper.ORecordValues
11-21 18:53:47.660 27304-27497/ W/System.err:     at .addons.sale.SalesDetail$SaleOrderOperation.doInBackground(SalesDetail.java:403)
11-21 18:53:47.660 27304-27497/ W/System.err:     at .addons.sale.SalesDetail$SaleOrderOperation.doInBackground(SalesDetail.java:282)
11-21 18:53:47.660 27304-27497/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
11-21 18:53:47.660 27304-27497/W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
11-21 18:53:47.660 27304-27497/W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
11-21 18:53:47.660 27304-27497/W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-21 18:53:47.660 27304-27497/W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-21 18:53:47.660 27304-27497/W/System.err:     at java.lang.Thread.run(Thread.java:856)

**Comment by dpr-odoo** [comment]
You can not directly cast ``HasMap`` to ``ORecordValues``

Try: 

```java
ORecordValues values= new ORecordValues();
values.addAll(data);
sale.getServerDataHelper().updateOnServer(values, record.getInt("id"));
```
https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/rpc/helper/ORecordValues.java#L72-L74
