### ISSUE TITLE
how to implement setOnValueChangeListener on OSelection field in odoo mobile framework

### ISSUE THREAD

**Issue by amar-teckzilla** [Odoo-mobile/framework#270]
Suppose i have 2 options in OSelection field eg Yes and No
If Yes is selected then make visible 2 more fields
If No is sellected then make visible 3 more filelds
Any example related to these was helpful..

**Comment by dpr-odoo** [comment]
@amar-teckzilla 

In framework customer detail form, when user click on ``is_company`` field and if it's ``true`` it will hide ``company_id`` field and it implement ``setOnValueChangeListener`` 

**Getting ``OField`` object for ``is_company`` field and adding value change listener which impliment ``setOnValueChangeListener``**
https://github.com/Odoo-mobile/crm/blob/master/app/src/main/java/com/odoo/addons/customers/CustomerDetails.java#L127-L128

In ``setOnValueChangeListener`` add the code for visibility change:

https://github.com/Odoo-mobile/crm/blob/master/app/src/main/java/com/odoo/addons/customers/CustomerDetails.java#L282-L289

**Comment by amar-teckzilla** [comment]
It not working in my case.
My code is some what like these
In Omodel i have column as folllow:
  OColumn product_type = new OColumn("Product Type", OSelection.class)
            .addSelection("equipment","Equipment")
            .addSelection("consumable", "Consumable");

and when i am refering your code in first field it either works sometime and when i am selecting second as cosumable it throws error and crash as null pointer.

**Comment by dpr-odoo** [comment]
@amar-teckzilla can you provide crash trace for error identification.

**Comment by adam-nadar** [comment]
Sir as you said it works good in OBoolean field but in our case we wan it on OSelection field
