### ISSUE TITLE
crashed after login

### ISSUE THREAD

**Issue by NrmeenTomoum** [Odoo-mobile/framework#276]
i tried v 2.3 framework it crashed after login why?

**Comment by dpr-odoo** [comment]
if you have **Instant Run enabled** in Android Studio you need to disable it (https://developer.android.com/studio/run/index.html#disable-ir)

**Comment by NrmeenTomoum** [comment]
syn data from server no customer retrieved on listview why?

**Comment by adam-nadar** [comment]
@NrmeenTomoum have u updated the authorities ??

**Comment by NrmeenTomoum** [comment]
no i just get framework and try to run it on my phone the first time it run and open customer list no customer found but there are customer in server  in the second time crashed after login

**Comment by NrmeenTomoum** [comment]
@dpr-odoo   i didn't have ability to disable instant run enabled,it is blocked

**Comment by adam-nadar** [comment]
<provider
            android:name="com.odoo.addons.customers.providers.CustomersSyncProvider"
            android:authorities="core.provider.content.sync.res_partner"
            android:label="@string/sync_label_customers"
            android:multiprocess="true" />


update ur manifest , xml model with same authorities


<sync-adapter xmlns:android="http://schemas.android.com/apk/res/android"
    android:accountType="com.odoo.auth"
    android:contentAuthority="core.provider.content.sync.res_partner"
    android:supportsUploading="true"
    android:userVisible="true" />

**Comment by NrmeenTomoum** [comment]
@adam-nadar  authorities updated i with ??

**Comment by dpr-odoo** [comment]
Go to **File** -> **Settings** -> **Build, Execute, Deployment** -> **Instant Run** -> **Disable it**


![aaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/7599886/20748062/bcd94130-b712-11e6-8a54-92efdd9abd14.png)

Again compile and run. If not solved than check your model authority strings: 

1. https://github.com/Odoo-mobile/framework/blob/master/app/src/main/AndroidManifest.xml#L85
2. https://github.com/Odoo-mobile/framework/blob/master/app/src/main/res/xml/customer_sync_adapter.xml#L3
3. https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/base/addons/res/ResPartner.java#L41-L42

each of the authority must be same.

**Comment by NrmeenTomoum** [comment]
Thanks @dpr-odoo  for your Screen shot but in my android studio didn't give me access to make it uncheck not clickable

**Comment by NrmeenTomoum** [comment]
tell me more about what authority  mean ??

**Comment by dpr-odoo** [comment]
https://developer.android.com/guide/topics/providers/content-provider-creating.html#ContentURI

**Comment by NrmeenTomoum** [comment]
thanks marry thanks @dpr-odoo  and @adam-nadar  it is worked

**Comment by DonFeraRRi** [comment]
I am having same trouble with it. Android App crashes after login. Please share the solution...

................. Log......................
06-06 18:16:21.854 23155-23155/com.odoo I/art: Late-enabling -Xcheck:jni
06-06 18:16:21.886 23155-23162/com.odoo E/art: Failed sending reply to debugger: Broken pipe
06-06 18:16:21.889 23155-23162/com.odoo I/art: Debugger is no longer active
06-06 18:16:21.889 23155-23162/com.odoo I/art: Starting a blocking GC Instrumentation
06-06 18:16:21.918 23155-23155/com.odoo W/System: ClassLoader referenced unknown path: /data/app/com.odoo-1/lib/arm
06-06 18:16:22.050 23155-23155/com.odoo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
06-06 18:16:22.212 23155-23170/com.odoo I/Adreno: QUALCOMM build                   : 48a5bf5, I15255e4b4a
                                                  Build Date                       : 02/22/17
                                                  OpenGL ES Shader Compiler Version: XE031.09.00.03
                                                  Local Branch                     : 
                                                  Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.019
                                                  Remote Branch                    : NONE
                                                  Reconstruct Branch               : NOTHING
06-06 18:16:22.219 23155-23170/com.odoo I/OpenGLRenderer: Initialized EGL, version 1.4
06-06 18:16:22.219 23155-23170/com.odoo D/OpenGLRenderer: Swap behavior 1
06-06 18:16:26.870 23155-23155/com.odoo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
06-06 18:16:30.761 23155-23155/com.odoo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
06-06 18:16:32.077 23155-23155/com.odoo D/AndroidRuntime: Shutting down VM
06-06 18:16:32.078 23155-23155/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.odoo, PID: 23155
                                                          java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
                                                              at com.odoo.core.rpc.helper.OdooVersion.parseVersion(OdooVersion.java:74)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper$3.onResponse(OdooWrapper.java:275)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:993)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:72)
                                                              at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                              at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
