### ISSUE TITLE
unsupported odoo version (Self Hosted Odoo Server)

### ISSUE THREAD

**Issue by messi89** [Odoo-mobile/framework#289]
Hi

I'm trying to use the odoo mobile version, according to this link : 
https://dharmangsoni.odoo.com/blog/blog-1/post/login-with-odoo-saas-account-in-odoo-mobile-2

I enter my server ip and port, my email and password but I can't login...

the app say : "unsupported odoo version" 

Odoo version : Version 9.0c-20160921 (Community Edition)

**Comment by dpr-odoo** [comment]
@messi89 

The blog is for messaging app, https://github.com/Odoo-mobile/messaging which supports odoo Oauth login with odoo's instances version up to 9.0 only, and current framework will not support oauth login with odoo instances. 

If your instance is 10.0+ you can directly login with your instance url and password.

If your server is not on saas platform, you can directly login with your Server URL and username, password. It supports 7.0 to 10.0 Odoo versions.

**Comment by messi89** [comment]
@dpr-odoo 

I'm on Odoo 9.0c-20160921 (Community Edition) (self hosted not a saas)  and not work with url/username/password

**Comment by dpr-odoo** [comment]
Hello @messi89 

We have tested application Odoo 9.0c (Community edition) and at our side its working fine.

**Comment by messi89** [comment]
so what's wrong with me :(

did you test with the app on google play ?

**Comment by messi89** [comment]
Hello @dpr-odoo 

so what's wrong with me :(

did you test with the app on google play ?

**Comment by dpr-odoo** [comment]
@messi89 which application you are talking about ??

**Comment by messi89** [comment]
@dpr-odoo this one https://play.google.com/store/apps/details?id=com.odoo.mobile

**Comment by dpr-odoo** [comment]
No, this application not support community version and it's not made on this framework. 

Supported versions:

★ Odoo 10.0 (Enterprise) 
★ Odoo   9.0 (Enterprise) - Some legacy features may not be supported

**Comment by messi89** [comment]
so I need to compile my version from this repo ?

**Comment by dpr-odoo** [comment]
It's fully native android framework to build android applications integrated with Odoo.
You can get more details on http://mobile.odoo.co.in/v2/
