### ISSUE TITLE
ModelRegistryUtils can't load App's package name

### ISSUE THREAD

**Issue by jiangzhixiao** [Odoo-mobile/framework#291]
Hi,when i use the latest code,the app can't startup. when i debug the code.i find in the ModelRegistryUtils line 22. ` String element = item.nextElement();`  the element never startwith app's packagename.see my screen shot
![image](https://cloud.githubusercontent.com/assets/7273487/21377834/7c37d19e-c77c-11e6-98c4-4a2e219ad4da.png)

**Comment by dpr-odoo** [comment]
@jiangzhixiao 

With Instant Run enabled in Android Studio registry will not work in Debug mode, but it will work fine in Released mode. Disable Instant Run https://goo.gl/lsfhq9 before build app.

**Comment by jiangzhixiao** [comment]
@dpr-odoo
Thank you very much `(*∩_∩*)′,you are my saviour,by the way ,can you give me some advise about issue #290

**Comment by jiangzhixiao** [comment]
@dpr-odoo
Thank you very much `(*∩_∩*)′,you are my saviour,by the way ,can you give me some advise about issue #290
