### ISSUE TITLE
How the admin account can sync all user data?

### ISSUE THREAD

**Issue by danhthong** [Odoo-mobile/framework#295]
Hi

I don't know how to sync all data of user by admin account.
Please give any suggestion if Framework can do it.
I'm newbie.

Thanks.

**Comment by adam-nadar** [comment]
@DanhThong have you refferd the official doc?
[http://mobile.odoo.co.in/v2/](url)

**Comment by danhthong** [comment]
@adam-nadar Yes. http://odoo-mobile-doc.readthedocs.io/en/latest/getting-started/working-with-odoo-mobile/components/addons.html#creating-sync-service

But i can't see the sync option for admin
