### ISSUE TITLE
How to call odoo api use react native?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#296]
hi all
How to call odoo api use react native? who know react native call odoo api how to do?

**Comment by adam-nadar** [comment]
@mikedream89 you use xmlrpc or JSONrpc

**Comment by mikedream89** [comment]
@adam-nadar 
thanks , could you give me example code ?

**Comment by adam-nadar** [comment]
`//String URL , db, user,pass ;int port


URL u = new URL("http",sp.getString("URL",""),sp.getInt("port",0), "/xmlrpc/common");
                XMLRPCClient xmlrpcClient = new XMLRPCClient(u);
                Object id=xmlrpcClient.call("login", sp.getString("db", ""), user, pass);
                return id.toString();
`
[https://github.com/gturri/aXMLRPC](url)
