### ISSUE TITLE
java.lang.SecurityException

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#303]
hi 
java.lang.SecurityException
caller uid 10306 is different than the authenticator's uid
com.odoo.core.support.OUser.fillFromAccount(OUser.java:58)
why some phones have this SecurityException, some phones no ?
thanks
@dpr-odoo

**Comment by dpr-odoo** [comment]
@mikedream89 
With odoo apps (build with framework) each application share same user (auth type) and when different application build on different machine, uid for that app is different. So when app try to get details from user object it throws SecurityException with message **caller uid 10306 is different than the authenticator's uid**

**Solution:**
Try to build on same machine or use same KeyStore (Signed apk with same keystore) for each of the application will solve this issue.

**Comment by mikedream89** [comment]
ok thanks @dpr-odoo
