### ISSUE TITLE
beginning of crash

### ISSUE THREAD

**Issue by Tanererkan06** [Odoo-mobile/framework#309]
![begining_](https://cloud.githubusercontent.com/assets/3882613/23101572/5351d1ce-f69f-11e6-9b01-2d8fdc8f33e8.png)

**Comment by Tanererkan06** [comment]
İ was run enabled disable it.(android studio)

**Comment by Tanererkan06** [comment]
@asa-odoo pls could be fix ?
 public void onLoadFinished(Loader<Cursor> loader, Cursor data) {
        try {
         mAdapter.changeCursor(data);

        if (data.getCount() > 0) {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    OControls.setGone(mView, R.id.loadingProgress);
                    OControls.setVisible(mView, R.id.swipe_container);
                    OControls.setGone(mView, R.id.data_list_no_item);
                    setHasSwipeRefreshView(mView, R.id.swipe_container, Customers.this);
                }
            }, 500);
        } else {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    OControls.setGone(mView, R.id.loadingProgress);
                    OControls.setGone(mView, R.id.swipe_container);
                    OControls.setVisible(mView, R.id.data_list_no_item);
                    setHasSwipeRefreshView(mView, R.id.data_list_no_item, Customers.this);
                    OControls.setImage(mView, R.id.icon, R.drawable.ic_action_customers);
                    OControls.setText(mView, R.id.title, _s(R.string.label_no_customer_found));
                    OControls.setText(mView, R.id.subTitle, "");
                }
            }, 500);
            if (db().isEmptyTable() && !syncRequested) {
                syncRequested = true;
                onRefresh();
            }
        }
        }
        catch(NullPointerException e)
        {
            System.out.print("NullPointerException caught");
        }
    }

**Comment by asa-odoo** [comment]
@Tanererkan06 
Looks like you have changed an application id from `com.odoo` to `com.modoo`
In case of that you also need to change customer authority in `xml` file from `com.odoo` to `com.modoo`

**Comment by Tanererkan06** [comment]
Thanx @asa-adoo for interest

**Comment by Tanererkan06** [comment]
doesn't any Change @asa-odoo  i did as like that .. :( 

;![ad](https://cloud.githubusercontent.com/assets/3882613/23233924/19d42ef8-f959-11e6-84b4-2b4627e9b500.png)

**Comment by adam-nadar** [comment]
@Tanererkan06 what abt manifest file ?? updated the authority in that?

null pointer may also raised when the table is not created?
also check tat out.....

**Comment by Tanererkan06** [comment]
@adam-nadar  i was clean project and skip this error. Now gives to me diffrent mistake .. have u any idea ?
thanx interest 
![r](https://cloud.githubusercontent.com/assets/3882613/23256158/f3c440b8-f9c6-11e6-9ada-74b471674c9d.png)

**Comment by Tanererkan06** [comment]
@adam-nadar  Manifest is True..  i was Build after that solve this problem but this time gives to me.. 
![r](https://cloud.githubusercontent.com/assets/3882613/23258183/ab14e918-f9cf-11e6-8ef7-b69107c1e225.png)

could i change again " com.odoo to com.zodoo " ?
