### ISSUE TITLE
use 'select' to search data from sqlite db very slowly

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#310]
Hi ,
 When db (sqlite) has very much data, i use 'select' to search , it will very slowly.
 How to fix the problem?
Who can give me some advices?

**Comment by AsKaeternam** [comment]
Hello dear,

Can you post your select query ?

**Comment by mikedream89** [comment]
Hello,
   select not slowly,  i debug find mForm.initForm(row) is slowly .

**Comment by jiangzhixiao** [comment]
the same problem when  in debug mode
my solution is : Don't set breakpoint on the initForm(row) row

**Comment by mikedream89** [comment]
i just add log before initForm(row) and add log after initForm(row), then i look at the log time,  find initForm is slowly
