### ISSUE TITLE
Values are false when refreshing

### ISSUE THREAD

**Issue by AsKaeternam** [Odoo-mobile/framework#312]
Hello dear,

Do you know why when refreshig a list with records, new records are fetched by values pass to false.

For example I've partners, Pierre Cardin, I swipe down the list, new records are fetched but Pierre Cardin pass to False, then to Pierre Cardin, then to False, then to Pierre Cardin, until the complete end of the synchronization ? It's not really userfriendly...

Do you also have the problem ? Do you have a solution for that ?

Best regards

![capture](https://cloud.githubusercontent.com/assets/16239356/23549013/79af6cd6-000a-11e7-917f-5adcfaf1891d.PNG)

**Comment by adam-nadar** [comment]
@AsKaeternam y don u user logger or debugger to check tat out.....
wat values are available in ur ODataRow...

**Comment by AsKaeternam** [comment]
Yes I do, but while data is loading and refreshing records permutly pass from values to false etc... until the end of the sync. At the end values are well displayed.

Thank you for your answer

**Comment by adam-nadar** [comment]
@AsKaeternam 
`@Override
public void onViewBind(View view, Cursor cursor, ODataRow row){
OLog.log(row.toString());
}`
why don u try tis 

when as you are trying to retrieve data from ODataRow with key is not available thatz y it is returning false...

**Comment by AsKaeternam** [comment]
The problem was that I've use adapter.swapCursor instead of adapter.changeCursor
