### ISSUE TITLE
Can able to add new model "CRM" in framwork-master

### ISSUE THREAD

**Issue by naitikvithlani** [Odoo-mobile/framework#339]
I am trying to create list of CRM leads same as list of customers.

I am getting error 
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri com.odoo.core.orm.OModel.uri()' on a null object reference `
On 
`return new CursorLoader(getActivity(), db().uri(),null, selection, selectionArgs, "name");`

Any solution ?

**Comment by mikedream89** [comment]
@naitikvithlani  what  are your android OS version?

**Comment by naitikvithlani** [comment]
@mikedream89 On Android 7.0
Thanks for your comment, but i just resolved this issue.

Now, I am able to see List of Leads & Opportunities in this project, Please find attached screen shots.

![image](https://user-images.githubusercontent.com/6597323/31882327-04965254-b804-11e7-9e26-c4fb54fd85f1.png)

![image](https://user-images.githubusercontent.com/6597323/31882332-0dd3f416-b804-11e7-85d0-d980b7d7da29.png)


Also, I implemented the **chatting feature** for odoo version 8, 9c, 9e, 10c, 10e, Find attached screen shots.

![image](https://user-images.githubusercontent.com/6597323/31882300-f24b05a4-b803-11e7-82e8-f10b0650836f.png)


![image](https://user-images.githubusercontent.com/6597323/31882285-e6a9da54-b803-11e7-96b0-ed681ccff463.png)

**Comment by enerik** [comment]
i am getting the same error . 
how did you fix it ?

**Comment by naitikvithlani** [comment]
Hello @enerik,

You can add any addon with follow the simple steps given in the link:

http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/addons.html#creating-addon-with-odoo-mobile

**Comment by mheros** [comment]
Hello, I'm getting this error. I've followed the example to add an addon with success, but I've not found how to add any other addon. I mean the correct 'parameters' to be used for each addon.

For example the parameter model_name, the correct value for AUTHORITY, and the correct values for AndroidManifest.xml file.

Many thanks for your help.
