### ISSUE TITLE
Do you know this APP？

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#350]
Hi guys,
   the APP is not has open source code??
  I think the APP is better.
![20171025164610](https://user-images.githubusercontent.com/11469375/31989648-7c1c669a-b9a5-11e7-94ec-e58c3ea5fd0c.png)

**Comment by naitikvithlani** [comment]
@mikedream89 This app name is [odoo,](https://play.google.com/store/apps/details?id=com.odoo.mobile&hl=en) Which is only for enterprise versions of odoo.

**Comment by mikedream89** [comment]
@naitikvithlani  thanks

**Comment by fanha99** [comment]
that app is just like a special browser, which is render the responsive theme of the EE version.

**Comment by ghost** [comment]
@fanha99 

Odoo Enterprise is Responsive. Odoo has used [`Mobile JavaScript`](https://www.odoo.com/documentation/11.0/reference/mobile.html) so nicely in `enterprise` flavor. It will work like charm even in Android WebView sample application too.

**Comment by mikedream89** [comment]
the app is good, but it is not open source. (；′⌒`)

**Comment by bitsnaps** [comment]
I believe this app has no "Offline" feature, which is one of the most requested feature and this is basically why we use native mobile so you can save data locally then synchronize when connection becomes available.

**Comment by jzahid** [comment]
Of course it has offline feature.

**Comment by naitikvithlani** [comment]
@jzahid This webview app of odoo does not have offline features.
![Screenshot_2020-11-28-15-00-45-386_com odoo mobile](https://user-images.githubusercontent.com/6597323/100498799-c0832480-318a-11eb-9228-8f2bf01c11e3.jpg)

**Comment by jzahid** [comment]
Yes it does not.

Le sam. 28 nov. 2020 09:33, Naitik Vithalani <notifications@github.com> a
écrit :
