### ISSUE TITLE
relation between two tables manyToOne

### ISSUE THREAD

**Issue by aymen6** [Odoo-mobile/framework#366]
i need to show the person name 
actually i show the id of person 

 public void onViewBind(View view, Cursor cursor, ODataRow row) {
        OControls.setText(view, R.id.name, row.getString("person_id"));
            }
there are a relation manyToOne between class (sanction) and (ResPartner)

in this class(sanction)
i put this code 
   OColumn person_id = new OColumn("name", ResPartner.class, OColumn.RelationType.ManyToOne);
he shows me  the id of person but  i need to show his name
what can i do ?

 "person_id": [
            81,
            " JackZ"
        ],

**Comment by fedache** [comment]
ODataRow resPartner = row.getM2ORecord("person_id").browse()

**Comment by aymen6** [comment]
hello , where can i put this ?

ODataRow resPartner = row.getM2ORecord("person_id").browse()

i rellay want to show the name of person not his id

this is method in fragement

public void onViewBind(View view, Cursor cursor, ODataRow row) {
    OControls.setText(view, R.id.name, row.getString("name"));
    OControls.setText(view, R.id.email, row.getString("message"));
    ODataRow resPartner = row.getM2ORecord("person_id").browse();
    OControls.setText(view, R.id.company_name,resPartner);

this is the class sanction who haves informations about person


public class Sanction extends OModel {
    public static final String TAG = Sanction.class.getSimpleName();
    public static final String AUTHORITY = "com.odoo.Person";
    OColumn message = new OColumn("message", OText.class).setRequired();;
    OColumn name= new OColumn("name", OVarchar.class).setSize(100);
    OColumn student_id= new OColumn("student_id", ResPartner.class,
OColumn.RelationType.ManyToOne);
    OColumn class_id= new OColumn("class_id", Classes.class,
OColumn.RelationType.ManyToOne);
    OColumn type_id= new OColumn("type_id", typee.class,
OColumn.RelationType.ManyToOne);




    //  @Odoo.Functional(store = true, depends = {"student_id"},
method = "storeCompanyName")
 //    OColumn student_id = new OColumn("s", OVarchar.class).setSize(100)
 //           .setLocalColumn();

    public Sanction(Context context, OUser user) {
        super(context,"proschool.sanction", user);
    //    setHasMailChatter(true);


    }
    /*public String storeCompanyName(OValues value) {
        try {
            if (!value.getString("student_id").equals("false")) {
                List<Object> student_id = (ArrayList<Object>)
value.get("student_id");
                return student_id.get(1) + "";
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }*/
    @Override
    public Uri uri() {
        return buildURI(AUTHORITY);
    }

}

i try to show the name but i can't  can you help me plz and thank you
if you need any more code i will put

**Comment by fedache** [comment]
public void onViewBind(View view, Cursor cursor, ODataRow row) {
 ODataRow resPartnerRow = row.getM2ORecord("person_id").browse();
 OControls.setText(view, R.id.name, resPartnerRow.getString("name"));
}

**Comment by aymen6** [comment]
doesn't work
java.lang.Integer cannot be cast to com.odoo.core.orm.OM2ORecord

**Comment by aymen6** [comment]
person_id

is a json array

**Comment by fedache** [comment]
person_id can't be a json array, its an integer -->
OColumn person_id = new OColumn("name", ResPartner.class, OColumn.RelationType.ManyToOne);

Its not required

**Comment by aymen6** [comment]
this is my fragment

@Override
public void onViewBind(View view, Cursor cursor, ODataRow row) {
    OControls.setText(view, R.id.name, row.getString("name"));
    OControls.setText(view, R.id.email, row.getString("message"));
  (ligne 131)  ODataRow resPartnerRow = row.getM2ORecord("student_id").browse();
    OControls.setText(view, R.id.company_name, resPartnerRow.getString("Name"));



}

and this is the class

public class Sanction extends OModel {
    public static final String TAG = Sanction.class.getSimpleName();
    public static final String AUTHORITY = "com.odoo.Etudiant";
    OColumn message = new OColumn("message", OText.class).setRequired();;
      OColumn name= new OColumn("name", OVarchar.class).setSize(100);
     OColumn class_id= new OColumn("class_id", Classes.class,
OColumn.RelationType.ManyToOne);
    OColumn type_id= new OColumn("type_id", typee.class,
OColumn.RelationType.ManyToOne);
    OColumn student_id = new OColumn("Name", ResPartner.class,
OColumn.RelationType.ManyToOne);



he shows me

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ClassCastException: java.lang.Integer cannot be cast to
com.odoo.core.orm.OM2ORecord
                                                              at
com.odoo.core.orm.ODataRow.getM2ORecord(ODataRow.java:69)
                                                              at
com.odoo.Etudiant.Student.onViewBind(PersonFragement.java:131)



what can i do

**Comment by aymen6** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ClassCastException: java.lang.Integer cannot be cast to
com.odoo.core.orm.OM2ORecord
                                                              at
com.odoo.core.orm.ODataRow.getM2ORecord(ODataRow.java:69)
                                                              at
com.odoo.Etudiant.Student.onViewBind(PersonFragement.java:131)

error in log

**Comment by aymen6** [comment]
!!
