### ISSUE TITLE
Unable to create record on server.

### ISSUE THREAD

**Issue by developpeurSTS** [Odoo-mobile/framework#382]
My recordings are present locally, 
but during synchronization, 
the recording does not come on the server.

Someone to a solution to offer me?

**Comment by ikerfah** [comment]
You sure that you fill all the required fields ?

**Comment by developpeurSTS** [comment]
yes I have completed the required fields.
However, I noticed that the id of the local record takes the value 0.

**Comment by ikerfah** [comment]
Go to Model class and check the method allowCreateOnServer ( or something like that ) returns true. And you sure that you set  the authority for your model ?( manifest(provider and service)-xml file)

**Comment by developpeurSTS** [comment]
That's what I just tried, and apparently it worked.

Thanks for your help.

**Comment by ikerfah** [comment]
Congratulate! You close the issue now.
