### ISSUE TITLE
Understanding Odoo Mobile Framework v2.0

### ISSUE THREAD

**Issue by wbo2012** [Odoo-mobile/framework#40]
Hello everybody
I downloaded the last version (v2.0) of Odoo Mobile Framework  and I found in com.odoo.addons.partners package :
-1- PartnersCursorLoader.java
-2-Partners.java
I didn't understand the difference between those two files
and  PartnersCursorLoader  used for what?
Any one can help me?
Thanks

**Comment by salouaEL** [comment]
hi wbo2012 please did you find any probleme to implement the framwork because when i import it to my IDE i face a lot of errors.
Kind regards

**Comment by dpr-odoo** [comment]
@wbo2012  here is developer documentation http://mobile.odoo.co.in/v2/

**Comment by kondasusmithareddy** [comment]
@dpr-odoo  Documentation Link is not working 404 Error.
