### ISSUE TITLE
Problem Many2One of self inside V1.0 

### ISSUE THREAD

**Issue by Devang-Targetint** [Odoo-mobile/framework#44]
Hi, 

I was just checking through the framework sync process, and what I found here is the many2one of the self is not working with v1.0 .

We have parent_id(company to which the partner(s) belongs) in res.partner class and so I have added parent_id in ResPartnerDB.java as : 

```
        columns.add(new OEColumn("parent_id", "Partner Company", OEFields
                        .manyToOne(new ResPartnerDB(mContext))));
```

And I am getting them in logcat entries while the sync process is running, but at the end they are not getting store in res.partner Table on OdooQLite.db.

Is this a bug or do I need to follow some steps to get data of many2One of the self? 

Any lights on this.

I will do thanks in advance.

**Comment by dpr-odoo** [comment]
No support for v1, Please migrate to v2. Thanks.
