### ISSUE TITLE
App not compatible with android 4.1.2

### ISSUE THREAD

**Issue by glusardi** [Odoo-mobile/framework#55]
As i saw on the minsdk is 14, this should be for 4.0 and higher, but i cant make it work on 4.1.2 or any other beside 4.4
This is working as intented? If so, please change the minsdk value.
Regards.

**Comment by fred0716** [comment]
I would like to install this app on motorola/symbol MC40 Android 1.4.1.
But it is not work.
Any recommendation?

**Comment by HectorFGarcia** [comment]
Same with 4.0.3

**Comment by SELKHOUFAIRI** [comment]
It works for me on mobile withe version 4.2.2

**Comment by if-alan** [comment]
Anyone got a solution for this problem?

**Comment by dpr-odoo** [comment]
can you check with latest update?
