### ISSUE TITLE
Sync many2many field

### ISSUE THREAD

**Issue by wbowbo** [Odoo-mobile/framework#56]
Hello everybody
I have a problem with field many2many on synchronisation of the ResPartner mobule
Trace like this:

02-16 21:05:28.453: E/SQLiteLog(19706): (1) no such column: category_id
02-16 21:05:28.453: I/OSyncAdapter(19706): Found 0 local entries for upload to server
02-16 21:05:29.943: W/System.err(19706): android.database.sqlite.SQLiteException: no such column: category_id (code 1): , while compiling: UPDATE res_partner SET company_id=?,phone=?,street=?,image_small=?,customer=?,date=?,write_date=?,city=?,id=?,state_id=?,create_date=?,odoo_name=?,name=?,supplier=?,street2=?,zip=?,website=?,country_id=?,category_id=?,email=?,is_company=?,is_dirty=?,local_write_date=?,comment=?,property_product_pricelist=?,mobile=? WHERE (_id=?)
02-16 21:05:29.973: W/System.err(19706):    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
02-16 21:05:29.973: W/System.err(19706):    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
02-16 21:05:30.843: W/System.err(19706):    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
02-16 21:05:31.043: W/System.err(19706):    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)

Any help please?

**Comment by wbowbo** [comment]
Any help please?

**Comment by dpr-odoo** [comment]
can you check with latest update?
