### ISSUE TITLE
framwork tutorial

### ISSUE THREAD

**Issue by jzahid** [Odoo-mobile/framework#59]
Hi every one, 
Is there any documentation or tutorial for the framework ?

**Comment by salouaEL** [comment]
hi jzahid i find this documentation : http://mobile.openerp.co.in/ it's for openerp v7 but there is some similarities with it and the odoo mobile framwork.

**Comment by jzahid** [comment]
Thank you, for the reply. I ve been already working with this one. It's not suitable for V8. There are a lot core changes in the framework.

**Comment by salouaEL** [comment]
yeah you are right, it has some similarities in code but surely it doesn't
work with odoo v8, do you try to work with odoo mobile framwork v1.0?

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Elève Ingénieur en Réseaux Informatiques et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-03-06 17:23 GMT+00:00 jzahid <notifications@github.com>:

**Comment by jzahid** [comment]
Yes, i do.

**Comment by maitsapo** [comment]
Any luck with finding tutorials? im new to this, may kindly please guide me as to where to find relevant tutorials on this framework

**Comment by redkyo017** [comment]
Any helps, please ?

**Comment by jzahid** [comment]
You can find the tutorials for th v1.0 of the framework here
http://mobile.openerp.co.in/
