### ISSUE TITLE
Bug in Partner syncing for database created without demo data

### ISSUE THREAD

**Issue by theprovensupport** [Odoo-mobile/framework#60]
Hi,

I've created new database without selecting "Load demonstration data" option. After the successful setup of the database, I've added few records in the "Contact" screen without adding any State or Country information for those records.

Now I've logged inside the Odoo mobile app with that database, but it somehow not recognizing any records which I've added in the contact screen. After some debugging I found that if I add any State or Country information in any record then it that record is getting fetched successfully by the Odoo mobile framework. 

I think this is the major bug in the framework and it will create issues to use the Odoo mobile framework for the database which are in the production environment.

Please help us to resolve this issue ASAP. Looking forward to your revert.

Thanks,
Parul

**Comment by dso-odoo** [comment]
Hi Parul,
      We tested the framework as you described. But we didn't find any such type of bug. I suggest you to test your module in mobile device. 

Thank You.

**Comment by SalouaELKHOUFAIRI** [comment]
hi Parul,
please tell me if you work with the odoo moile framwork 1.0 or odoo mobile
framwork 2.0?
best regards

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Elève Ingénieur en Réseaux Informatiques et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-03-12 5:57 GMT+00:00 Dimple Soni <notifications@github.com>:

**Comment by theprovensupport** [comment]
hi dso-odoo,

Thank you very much for your immediate reply. We are already testing module in Mobile device only. but finding above explained bug. 

Have you created new database without selecting "Load demonstration data" option? In that, if you add any customer without adding any State or Country information, that record will not be sync. you will not find this record in mobile app after syncing.

Thanks,
Parul

**Comment by theprovensupport** [comment]
hi  SalouaELKHOUFAIRI ,

Thank you very much for your reply.
I am using odoo mobile framework 2.0

Thanks,
Parul

**Comment by dso-odoo** [comment]
Hello Parul,
Yes, we have tested it having database containing no demo data. Created contact as you described and synced, and it worked. We didn't found any bug. And we had perform this in  odoo mobile framework 2.0.
So, I suggest you to check it again :)

Thank You.

**Comment by jzahid** [comment]
Hi, Parul
I've tested both versions 1.0 and 2.0 on mobile device and don't have the bug you described. You can at least copy/past the log output you had.

**Comment by SalouaELKHOUFAIRI** [comment]
hi everyone,
According to me i couldn't work with odoo mobile framwork 2.0 when i export
it to my IDE, i didn't find the R file , I thinnk it's because i use an
android API different? if anyone can help me.
kind regards

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Elève Ingénieur en Réseaux Informatiques et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-03-12 11:55 GMT+00:00 jzahid <notifications@github.com>:

**Comment by jzahid** [comment]
what IDE are you using ? try to clean the project and rebuild it



*SSLL, Intégrateur Odoo.*

*Intégration de Services. *
*BI and IT consulting.*
j.zahid@auriumtechnologies.com
tél  0661360233 - 0636898882
fax 0528215738
www.auriumtechnologies.com

**Comment by jzahid** [comment]
what IDE are you using ? try to clean the project and rebluid it again.

**Comment by SalouaELKHOUFAIRI** [comment]
I'm using eclipse, please can you tell me with which API android you are
working?

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Elève Ingénieur en Réseaux Informatiques et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-03-12 15:06 GMT+00:00 jzahid <notifications@github.com>:

**Comment by jzahid** [comment]
ADT plugin for eclipse is no more maintained. Android Studio is the official tool now.
You'd better to switch to it. It uses gradle scripts (it's maven like ) as building tool. more powerful to resolve all project dependecies ( min max sdk vesion  target).

**Comment by SalouaELKHOUFAIRI** [comment]
ok thank you a lot

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Elève Ingénieur en Réseaux Informatiques et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-03-12 15:23 GMT+00:00 jzahid <notifications@github.com>:
