### ISSUE TITLE
What can Odoo-mobile do?

### ISSUE THREAD

**Issue by heshamfm** [Odoo-mobile/framework#64]
Hi,
May I ask a few questions:

1- Are there any tutorials for the ORM?
2- Can I use Python to create mobile modules?
3- What mobile modules are produced using this framework?

Thanks

**Comment by jzahid** [comment]
Hi
1 - you can check the documentation for branch 1.0 here : http://mobile.openerp.co.in/
2-  the framework is written in java. so to create a new module you should code in java/xml.
3- any module created with this framework is just a representation to an existting  model/module in your server side implemtation. So you need to have a functionning module already installed on your server and then beign to create a mobile corresponding module using this framework.

**Comment by dpr-odoo** [comment]
:+1: @jzahid

**Comment by heshamfm** [comment]
Hi @jzahid ,

Thanks a lot.

What level of Java experience is required to do that?

**Comment by jzahid** [comment]
Hi @heshamfm 
It's java android project. You will need basically to be familiar with android devloppement concepts, essentially (Android API, UI design in xml, and andoid Views life cycle ). All the rest is just  java you already know.
Here is wher to start. http://developer.android.com/training/index.html 
Good luck

**Comment by heshamfm** [comment]
thanks a lot @jzahid

**Comment by jzahid** [comment]
you're welcome :-)  @heshamfm

**Comment by aman-gautam** [comment]
http://mobile.openerp.co.in/ is no longer functional. @jzahid Can you please update the url?

**Comment by dpr-odoo** [comment]
Its, http://mobile.odoo.co.in

**Comment by dpr-odoo** [comment]
Hello,

New documentation for version 2.0 is available. Visit http://mobile.odoo.co.in/v2

**Comment by heshamfm** [comment]
a,
    a:visited {
        color: #D26000;
        text-decoration: none;
    }


    
        
            
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                        
                    
                
            
            
            
            
                
                    
                        

    
        
             
        
    


	

    
        
            
                
                    
                
            
            
                
                    Join me on PeoplePerHour
                
            
        
        
            
                
                    
                
                
                    PPH looks very promising after LinkedIn actually helped us with nothing !
                
            
        
    

 



    
    	
    		
    			
                	ACCEPT INVITATION
            	
        	
        
    


                    
                
            
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                
                                            
                                        
                                        
                                            
                                                
                                                    
                                                        © 2007 - 2015 PeoplePerHour All rights reserved                                                    
                                                    
                                                        This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here

**Comment by heshamfm** [comment]
a,
    a:visited {
        color: #D26000;
        text-decoration: none;
    }


    
        
            
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                        
                    
                
            
            
            
            
                
                    
                        


    
    
        
          News about Hesham and other latest on PeoplePerHour
        
      

      
        
      

      
        
          
          
      
    


Hello,
Hesham has been active on PeoplePerHour for 5 days now and they've invited you to join!
Accept the invitation today and get 10% off your first purchase on PeoplePerHour... it's great to have friends with benefits, right?




    
    	
    		
    			
                	Join now
            	
        	
        
    


Here's some of the latest activity on PeoplePerHour that you'll find interesting




    
        

    
        
            
                
        
    
    
        
            
                
                    Get any video YouTube VlRAL,Social Media promotion and SEO
                
            
        
    
    
        
            
                
                    
                        
                            
                                
                            Marketing G.
                        
                        
                            
                                
                                    
                                        $29
                                    
                                
                            
                        
                    
                
            
        
    

     
        

    
        
            
                
        
    
    
        
            
                
                    Add 1000 genuine YouTube subscribers to your channel
                
            
        
    
    
        
            
                
                    
                        
                            
                                
                            Nenad T.
                        
                        
                            
                                
                                    
                                        $69
                                    
                                
                            
                        
                    
                
            
        
    

    
 

    
        

    
        
            
                
        
    
    
        
            
                
                    Retouch 10 photo shoot for Photographer professional
                
            
        
    
    
        
            
                
                    
                        
                            
                                
                            Hung L.
                        
                        
                            
                                
                                    
                                        $30
                                    
                                
                            
                        
                    
                
            
        
    

     
        

    
        
            
                
        
    
    
        
            
                
                    1000 Google+ Followers Or 3000 YouTube views OR 2500 Instagr...
                
            
        
    
    
        
            
                
                    
                        
                            
                                
                            MD.MESBAHUL A.
                        
                        
                            
                                
                                    
                                        $10
                                    
                                
                            
                        
                    
                
            
        
    

    
 

    
        

    
        
            
                
        
    
    
        
            
                
                    Provide career coaching
                
            
        
    
    
        
            
                
                    
                        
                            
                                
                            Sam D.
                        
                        
                            
                                
                                    
                                        $50
                                    
                                
                            
                        
                    
                
            
        
    

     
        

    
        
            
                
        
    
    
        
            
                
                    Provide 100 email'Ids of C-Level Executive (CEO,CFO,CIO,COO)...
                
            
        
    
    
        
            
                
                    
                        
                            
                                
                            Ghanshyam S.
                        
                        
                            
                                
                                    
                                        $35
                                    
                                
                            
                        
                    
                
            
        
    

    



    
        
            
                Kind Regards,
                The PPH Team
            
        
    

                    
                
            
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                
                                            
                                        
                                        
                                            
                                                
                                                    
                                                        © 2007 - 2015 PeoplePerHour All rights reserved                                                    
                                                    
                                                        This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here
