### ISSUE TITLE
Problem importing

### ISSUE THREAD

**Issue by farokovic** [Odoo-mobile/framework#73]
Hello
When i import the project "framework-master" in android studio, i found some problems in com.odoo.core.service.OSyncAdapter:
this import are not reconaized
import odoo.Odoo;
import odoo.helper.ODomain;
import odoo.helper.ORecordValues;
import odoo.helper.OdooFields;
import odoo.helper.utils.gson.OdooRecord;
import odoo.helper.utils.gson.OdooResult;
any help?

**Comment by dso-odoo** [comment]
Hi @farokovic 
After importing framework-master once you need to build your project.
 Menu -> **Build -> Rebuild Project**
will solve your project.

**Comment by farokovic** [comment]
i did it before and the problem persists

**Comment by dso-odoo** [comment]
Is there any trace or log you receive ?

**Comment by farokovic** [comment]
![image](https://cloud.githubusercontent.com/assets/7383454/8107306/a7782832-1048-11e5-8856-0d99d4de65f2.png)

**Comment by farokovic** [comment]
the build is successful

**Comment by dso-odoo** [comment]
Is your problem completely solved? If yes than close the issue.

**Comment by farokovic** [comment]
no isn't solved solved, the problem still there

**Comment by dso-odoo** [comment]
Open **app/build.gradle** file and change **applicationId** "com.odoo" to your package name and also change the **applicationName** under defaultConfig.
gradle is preventing to build, because you don't have changed the build configuration.

**Comment by farokovic** [comment]
![image](https://cloud.githubusercontent.com/assets/7383454/8107640/1e6fec66-104b-11e5-84ba-075cb6f8910e.png)

i change them from the begining and also the same problem. there's an other file to modify it?

**Comment by dpr-odoo** [comment]
Hello @farokovic 

I think your all dependencies built successfully. If still you are getting the error. Just restart your project.

**Comment by farokovic** [comment]
the same problem -_-

**Comment by dpr-odoo** [comment]
Hello @farokovic 

At our side it's working fine. All dependencies are downloaded automatically. Are you getting same error in **com.odoo.core.orm.ServerDataHelper** ?? If not, than just run your app.

**Comment by farokovic** [comment]
hello @dpr-odoo 
the app run without any problems but when i need to get data from server i got nothing and to add data from mobile to server.

**Comment by SalouaELKHOUFAIRI** [comment]
hi @farocovic u have to check your model the attributes must have the same name of fields like in python.

**Comment by shynejocef** [comment]
Hi , I had the same issue not recognizing all Odoo imports as show in the image. Any idea??
<img width="960" alt="odoo" src="https://cloud.githubusercontent.com/assets/8074379/11613421/d7f094a2-9c45-11e5-98d2-b353fe15c46b.png">

**Comment by dpr-odoo** [comment]
Please update with latest commits. Thanks.
