### ISSUE TITLE
IllegalStateException:Fragment already active

### ISSUE THREAD

**Issue by HectorFGarcia** [Odoo-mobile/framework#76]
Using fragments with bundle and adding them to the backstate eventually causes that error because, in the OFragmentUtils class, the method starFragment() tries to use fragment.setArguments() BEFORE check if the fragment is still active.

**Comment by SrushtiPatel** [comment]
I am also facing this problem. Any suggestions?? Or is there any other way to call fragment using another fragment or to maintain fragment backstack?

**Comment by dpr-odoo** [comment]
Can you check with latest update. If issue there you can reopen issue. thanks.
