### ISSUE TITLE
How to get data from ManyToMany field

### ISSUE THREAD

**Issue by sailing135** [Odoo-mobile/framework#79]
Hello everybody, 

please help me, how to get data from ManyToMany field.

Ex: in CalendarEvent.java,  
OColumn partner_ids = new OColumn("Attendees", ResPartner.class, OColumn.RelationType.ManyToMany);

Then in CalendarDashboard.java,
    public Loader<Cursor> onCreateLoader(int id, Bundle data) {
          ...
          where += "and (partner_ids in ?)";
          ...
}
=> crash, because partner_ids no such column

Any help please ?

**Comment by tks-dp** [comment]
Here is the reference example of Many2Many 

the 'attachment_ids' from crm;

https://github.com/Odoo-mobile/crm/blob/1e06c465bf4a624ebfd3afe25e5a13109d47cc5b/app/src/main/java/com/odoo/base/addons/mail/widget/MailDetailDialog.java : 
Line no 81+

the 'partner_ids' from messaging
https://github.com/Odoo-mobile/messaging/blob/0fc384ef747802516e65fe848c4aab8212abc3bd/src/com/odoo/addons/mail/services/MailSyncService.java 
Line no 77+

Hope this will help you!!

**Comment by dpr-odoo** [comment]
Hello @sailing135

As you mention, you are tyring to give condition on **ManyToMany** column. That actually does not exist in database table. But, system had created seperate table for maintaining the relation between two different tables. So, it's not possible to directly give condition using where. 

The way you are trying to get record by conditioning on relation column (such as ManyToMany and OneToMany) is not possible with use of **CursorLoader** mechanism.

A **CursorLoader** runs an asynchronous query in the background against a **ContentProvider**, and returns the results in **Cursor** object.

How to do that?
---------------

**For that, You need to create one join query.**

CursorLoader works with **ContentProvider**. You can find tutorial for how to create custom provider for your model. Also for execute your query you need to create one custom **URI** that will invoke your custom query with join and return value in cursor.

Please refer this link to understand how to create custom provider and your own URI to execute your required query with **CursorLoader**

http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/base-classes.html#basemodelprovider-java

Also here is sample code for execute query:

Note applicaiton: 

https://github.com/Odoo-mobile/notes/blob/master/app/src/main/java/com/odoo/addons/notes/providers/NoteProvider.java#L54

Refering the method, which returns cursor.

https://github.com/Odoo-mobile/notes/blob/master/app/src/main/java/com/odoo/addons/notes/models/NoteNote.java#L95,L105

Hope this help

**Comment by sailing135** [comment]
thanks all so much, I will try it !!

**Comment by rkhoudi** [comment]
In Notes.java , it is not clear how you did use CursorLoader to fetch data from the two different tables ( notes and tags in your project ) , would you explain it more please?
