### ISSUE TITLE
Cannot fetch partner from server

### ISSUE THREAD

**Issue by jay009id** [Odoo-mobile/framework#80]
Hi, I deployed odoo-mobile. After login, I cannot see any customer that has already in odoo. In my odoo server, I've create Sales Order also. Unfortunately, customer still cannot sync from server. I think I face same problem with issue #60. As info, I'm using odoo 8 and odoo mobile v2. Can someone guide me whats wrong or am I miss something? Thank you.

**Comment by jay009id** [comment]
No one can explain it?

**Comment by GeluB** [comment]
I'm having the same problems. The customers are not imported.
It must be something in the code cause i added tasks as shown in the documentation and it worked.

**Comment by yueming** [comment]
I'm having the same problems.

**Comment by yueming** [comment]
I solved it by making fix below:
1. Modify framework-master\app\src\main\res\xml\customer_sync_adapter.xml
    a. android:contentAuthority is wrong, change it to your correct provider authority, for example, mine is com.odoo.test.core.provider.content.sync.res_partner. Don't use ${applicationId}, it does not work. 
    b. android:isAlwaysSyncable="true".
2. Modify framework-master\app\src\main\java\com\odoo\SettingsActivity.java
    Change lst.authority.contains("providers") to lst.authority.contains("provider").
3. In app, enter Settings -> Sync Settings -> <Your Account>, tick Sync Customers.

**Comment by jay009id** [comment]
Excellent! It works. Thanks @yueming .

**Comment by edelfino** [comment]
Thank you! It worked for me too!
