### ISSUE TITLE
Building failed in Studio v1.3 (drawable-hdpi-v4/ic_launcher.png: error: Duplicate file)

### ISSUE THREAD

**Issue by yueming** [Odoo-mobile/framework#81]
Studio v1.3 uses gradle 2.4 which requires gradle plugin 1.2.0 (or newer). 

There will be an error when building with gradle plugin 1.2.0 like this:
  .../debug/drawable-hdpi-v4/ic_launcher.png: error: Duplicate file.
  .../drawable-hdpi/ic_launcher.png: Original is here. The version qualifier may be implied.

**Comment by dnia** [comment]
intro_slider_lib---> androidManifest.xml delete : 
android:icon="@drawable/ic_launcher"

**Comment by SELKHOUFAIRI** [comment]
hi,
please how can i diplay the group of the connected user in odoo mobile framework

Regards

**Comment by dnia** [comment]
hi 
in table "res_users" you can find all users... in this table exist login_date that save last login date of each user
