### ISSUE TITLE
On odoo-rpc-v3 when I call the listDatabases method before logging in I get an exception

### ISSUE THREAD

**Issue by Gorkygd** [Odoo-mobile/framework#83]
Isn't the list databases function supposed to be able to be called without authenticating at first?

When I try using it without having logged myself in I get an exception within the library. (trying to invoke a method on a null object)

**Comment by dpr-odoo** [comment]
@Gorkygd 

No, you don't need to authenticate for getting database list for server. It can be done in two way:

**With background task**

```
new AsyncTask<Void,Void,Void>(){

    @Override
    protected Void doInBackground(Void... params) {
        Odoo odoo = Odoo.createInstance(context, "http://192.168.199.101:8069");
        List<String> dbs=  odoo.getDatabaseList();
        Log.v("Databases: ", dbs.toString());
        return null;
    }
}.execute();
```

**With callback**

```
Odoo odoo = Odoo.createInstance(this, "http://192.168.199.101:8069");
odoo.getDatabaseList(new IDatabaseListListener() {
    @Override
    public void onDatabasesLoad(List<String> list) {
        Log.v("Databases: ", list.toString());
    }
});

```

**Note:** Use latest rpc library. Bug has been fixed in last commit.  https://github.com/Odoo-mobile/framework/commit/2f328cae00f403182e4b40b5466094078dcbb12d

**Comment by Gorkygd** [comment]
Ok thank you. Last question, since I am not sure on how to use this library is it's source code hosted somewhere? Or perhaps a documentation? (for example I do not now how to properly fill the OArguments object)

**Comment by Gorkygd** [comment]
I used both of your implementations and yet I get this:

08-20 05:03:43.308: E/AndroidRuntime(12292): Caused by: java.lang.NullPointerException
08-20 05:03:43.308: E/AndroidRuntime(12292): 	at odoo.wrapper.OdooWrapper.getDatabaseList(OdooWrapper.java:365)
08-20 05:03:43.308: E/AndroidRuntime(12292): 	at com.***.support.***ServerConnection$1.doInBackground(***ServerConnection.java:87)
08-20 05:03:43.308: E/AndroidRuntime(12292): 	at com.***.support.***ServerConnection$1.doInBackground(***ServerConnection.java:1)
08-20 05:03:43.308: E/AndroidRuntime(12292): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-20 05:03:43.308: E/AndroidRuntime(12292): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-20 05:03:43.308: E/AndroidRuntime(12292): 	... 4 more

**Comment by dpr-odoo** [comment]
@Gorkygd Have you replaced rpc library with latest one ?

**Comment by Gorkygd** [comment]
Ah thanks you were right. Now everything works good. Issue solved.

Thank you for your help.

Good day.
