### ISSUE TITLE
On odoo-rpc-v3 when I call the installedOnServer method I get an exception

### ISSUE THREAD

**Issue by daramousk** [Odoo-mobile/framework#85]
Now, when I try to query the server for a module's existance I get a null pointer exception inside the library. Here is the stack trace:

08-24 02:23:37.202: E/AndroidRuntime(2040): Caused by: java.lang.NullPointerException
08-24 02:23:37.202: E/AndroidRuntime(2040):     at odoo.wrapper.OdooWrapper.installedOnServer(OdooWrapper.java:892)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at com.[].util.RemoteModelCheck.moduleExists(RemoteModelCheck.java:13)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at com.[].Dashboard.onCreate(Dashboard.java:52)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.support.v4.app.Fragment.performCreate(Fragment.java:1481)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:908)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:571)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.app.Activity.performStart(Activity.java:5241)
08-24 02:23:37.202: E/AndroidRuntime(2040):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
08-24 02:23:37.202: E/AndroidRuntime(2040):     ... 11 more

**Comment by Gorkygd** [comment]
Ok. By decompiling the file and searching through this happens because the module does not exist on the server. (since under the hood the searchRead method returns null). But shouldn't there be an exception handling mechanism that informed the user of the module's non existance?

thanks.

**Comment by koz01** [comment]
D:\KZO\Tablet Mobile\Realm\Tools and Framework\Odoo Mobile Framework\framework-master\app\src\main\java\com\odoo\base\addons\ir\IrAttachment.java

Error:(40, 8) error: A RealmClass annotated object must be derived from RealmObject

**Comment by dpr-odoo** [comment]
can you check with latest update.
