### ISSUE TITLE
How to remove login ?

### ISSUE THREAD

**Issue by sailing135** [Odoo-mobile/framework#88]
Hi every body !!
In odoo mobile framework, How to remove login ?
please help me!
thanks all !

**Comment by dnia** [comment]
hi
can you More explanation? always login with one account?

**Comment by daniahalsharif** [comment]
sdf

**Comment by sailing135** [comment]
hi @dnia !
My idea is don't need login but still can view content.
please help me!

**Comment by dnia** [comment]
each company have a unique database, and access to this impossible without login! Maybe I'm wrong

**Comment by dpr-odoo** [comment]
For odoo, you can not access data without login but you can access with public controller which returns your required data also you can do it with default user credential that used for getting data from server and display to your application.
