### ISSUE TITLE
 "no country selected"  not working

### ISSUE THREAD

**Issue by dnia** [Odoo-mobile/framework#89]
hi
on country field if select "no country selected" than country_id change to false ... by sync value not change on server! select other value work fine but select "no .... selected" not work

**Comment by dnia** [comment]
any body help? please

**Comment by iamphamduyhung** [comment]
Hi @dnia,
I have the same problem with my ManyToOne column. Did you solve this?

**Comment by dpr-odoo** [comment]
Issue fixed in update.
