### ISSUE TITLE
Update data on server

### ISSUE THREAD

**Issue by Carlos-Domatix** [Odoo-mobile/framework#92]
Hello. I'm working with that framework but I have a problem. I don't know how can I update on the server my new values when I edit and save it on a form.

New values are saved on local database but not in the server.

Any help or tutorial? Thanks.

**Comment by SalouaELKHOUFAIRI** [comment]
Hi Carlos I think u didn't do a refresh by swipping from up to down in
order to synchroniz values in the server.
ᐧ

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Ingénieur d'état en Informatique et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-09-16 9:59 GMT+00:00 Carlos Alba <notifications@github.com>:

**Comment by Carlos-Domatix** [comment]
I have done it. But it still not working.

**Comment by SalouaELKHOUFAIRI** [comment]
have u already check the attributes of your classes if they are the same in
the android app?
ᐧ

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Ingénieur d'état en Informatique et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-09-16 10:22 GMT+00:00 Carlos Alba <notifications@github.com>:

**Comment by Carlos-Domatix** [comment]
I'm making a new addon so I have added some new classes and I can get information from the server but I can't send anything. Customer addon, for example, works ok, but not my addon.

**Comment by NguyenAnhTuyen** [comment]
I meet same problem with Carlos-Domatix, Can anybody help me ? Thanks !

**Comment by SrushtiPatel** [comment]
Did you get any error at the time of sync operation? Most of the time this happens when we have not put correct values for fields or for relational records. May be you are missing to assign some values!!

**Comment by dpr-odoo** [comment]
Many fix done in recent commits. can you check with latest update.
