### ISSUE TITLE
One2Many Field breaks sync operation

### ISSUE THREAD

**Issue by shangx** [Odoo-mobile/framework#93]
If i ignore the one2many fields which my odoo module has, and I don't declare them in the java class, the sync operation works fine, I can retrieve all data from server , and can also save changes and update on the server.

If I try to implement the one2many fields, even though I can retrieve the field data from the server, I can no longer update any of the other fields on the server. I can see the changes locally, but not on server.

**Comment by dpr-odoo** [comment]
can you check with latest update?
