### ISSUE TITLE
update data in server Framework V3

### ISSUE THREAD

**Issue by farokovic** [Odoo-mobile/framework#96]
How to update oneTwoMany data in srever. 
Example: i add task.work in mobile and synchronize in server and update a kanban_state for a project.rask?

**Comment by adam-nadar** [comment]
@farokovic with the help of RelValues class
u can update the local DB values
and the it will get synchronize on server
http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/working-with-relation-records.html
