### ISSUE TITLE
Synchronize data from mobile to Odoo

### ISSUE THREAD

**Issue by danielDomatix** [Odoo-mobile/framework#97]
Hello, I am Daniel.
Now I am programing a Odoo mobile application and I have a problem because I can't synchronize data from mobile to Odoo however to Odoo from mobile work good.

Could you help my with the application?

Sorry for my English I'am from Spain.

**Comment by Kelbethor** [comment]
Hola Daniel.
Quizás que sea un pelín amplia la descripción de esta incidencia. Si indicas que modelo intentas sincronizar o colocas un stacktrace del error se pudiera hacer algo más. 
Alguna columna one2many? (Es un tema recurrente en los problemas de sincronización en esa dirección)

Maybe your issue description it's a bit too wide. You should point the model you're syncing or include a StackTrace from debug to get some help.
Is it one2many column involved? (Recurring topic in mobile-to-server sync direction)

**Comment by shangx** [comment]
Yes, daniel is working on same project as me, so his issue is also with the one2many column :)

**Comment by dnia** [comment]
check server and mobile time!

**Comment by lakshman12345** [comment]
Hi Kelbethor,
                   I am new to android devolopment can you please tell me where to give the model name in my android application in order to sync it with web application.

**Comment by Kelbethor** [comment]
Well, i'm newbie in this subject too. LOL. You should asume this project guidelines reading code. In order to set new models you should ser up sync adapter, model provider and data model itself.
To implement new models should inherit com.odoo.core.orm.OModel class.

**Comment by kasim1011** [comment]
Hey, Does your emulator or phone running lower version than **Kitkat** than you should see [this](https://github.com/Odoo-mobile/framework/issues/165#issuecomment-219676006).

**Comment by dpr-odoo** [comment]
Similar issue will be fixed in #165
