### ISSUE TITLE
Release bugs with proguard settings

### ISSUE THREAD

**Issue by Kelbethor** [Odoo-mobile/framework#99]
Serveral logcat entries from release build complains about models constructors not being found nor functional fields (and so, failed syncs) and some googling and it seems proguard is removing them.

``` java
-keepclassmembers public class * extends com.odoo.core.orm.OModel {
    *;
}
```

rule added to proguard-rules.pro worked for me. I have no great knowledge about proguard so I think there are more optimal rules to achieve this.

**Comment by dpr-odoo** [comment]
Its added to framework https://github.com/Odoo-mobile/framework/blob/master/app/proguard-rules.pro#L44
